_NT_COMPETITION_KEYS = {'Nationalmannschaft', 'Nationalkader'}

_NATIONALITY_CONFEDERATION = {
    'Albanien':             'uefa',
    'Belgien':              'uefa',
    'Bosnien-Herzegowina':  'uefa',
    'Dänemark':             'uefa',
    'Deutschland':          'uefa',
    'England':              'uefa',
    'Estland':              'uefa',
    'Finnland':             'uefa',
    'Frankreich':           'uefa',
    'Griechenland':         'uefa',
    'Irland':               'uefa',
    'Island':               'uefa',
    'Italien':              'uefa',
    'Kosovo':               'uefa',
    'Kroatien':             'uefa',
    'Luxemburg':            'uefa',
    'Montenegro':           'uefa',
    'Niederlande':          'uefa',
    'Nordmazedonien':       'uefa',
    'Norwegen':             'uefa',
    'Österreich':           'uefa',
    'Polen':                'uefa',
    'Portugal':             'uefa',
    'Russland':             'uefa',
    'Schottland':           'uefa',
    'Schweden':             'uefa',
    'Schweiz':              'uefa',
    'Serbien':              'uefa',
    'Slowakei':             'uefa',
    'Slowenien':            'uefa',
    'Spanien':              'uefa',
    'Tschechien':           'uefa',
    'Türkei':               'uefa',
    'Ukraine':              'uefa',
    'Ungarn':               'uefa',
    'Wales':                'uefa',
    'Argentinien':          'conmebol',
    'Brasilien':            'conmebol',
    'Ecuador':              'conmebol',
    'Kolumbien':            'conmebol',
    'Suriname':             'conmebol',
    'Ägypten':              'caf',
    'Algerien':             'caf',
    'Angola':               'caf',
    'Burkina Faso':         'caf',
    'DR Kongo':             'caf',
    'Elfenbeinküste':       'caf',
    'Gambia':               'caf',
    'Ghana':                'caf',
    'Guinea':               'caf',
    'Guinea-Bissau':        'caf',
    'Kamerun':              'caf',
    'Kongo':                'caf',
    'Liberia':              'caf',
    'Libyen':               'caf',
    'Mali':                 'caf',
    'Marokko':              'caf',
    'Nigeria':              'caf',
    'Senegal':              'caf',
    'Tansania':             'caf',
    'Togo':                 'caf',
    'Tunesien':             'caf',
    'Australien':           'afc',
    'Indonesien':           'afc',
    'Irak':                 'afc',
    'Japan':                'afc',
    'Palästina':            'afc',
    'Philippinen':          'afc',
    'Südkorea':             'afc',
    'Syrien':               'afc',
    'Costa Rica':           'concacaf',
    'Curacao':              'concacaf',
    'Dominikanische Republik': 'concacaf',
    'Guadeloupe':           'concacaf',
    'Kanada':               'concacaf',
    'Vereinigte Staaten':   'concacaf',
}

_CONFEDERATION_BADGE = {
    'uefa':     'game/images/competitions/nt-uefa.png',
    'conmebol': 'game/images/competitions/nt-conmebol.png',
    'caf':      'game/images/competitions/nt-caf.png',
    'afc':      'game/images/competitions/nt-afc.png',
    'concacaf': 'game/images/competitions/nt-concacaf.png',
}


def nt_competition_logo(nationality):
    conf = _NATIONALITY_CONFEDERATION.get(nationality or '')
    return _CONFEDERATION_BADGE.get(conf, 'game/images/competitions/nationalmannschaft.svg')


def competition_logo_static_path(competition, nt_nationality=None):
    if competition in _NT_COMPETITION_KEYS:
        return nt_competition_logo(nt_nationality)
    assets = {
        '1. Bundesliga': 'game/images/competitions/bundesliga.png',
        'Bundesliga': 'game/images/competitions/bundesliga.png',
        'Websoccer Liga': 'game/images/competitions/websoccer-liga.svg',
        'DFB-Pokal': 'game/images/competitions/dfb-pokal.png',
        'Pokal': 'game/images/competitions/dfb-pokal.png',
        'Champions League': 'game/images/competitions/champions-league.png',
        'CL': 'game/images/competitions/champions-league.png',
        'Supercup': 'game/images/competitions/supercup.png',
        'Europa League': 'game/images/competitions/europa-league.png',
        'EL': 'game/images/competitions/europa-league.png',
        'Europa Conference League': 'game/images/competitions/europa-conference-league.png',
        'ECL': 'game/images/competitions/europa-conference-league.png',
    }
    return assets.get(competition, '')
