"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from django.core.management.utils import get_random_secret_key

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _env_bool(key, default=False):
    """Parse a truthy environment flag (1/true/yes/on)."""
    val = os.environ.get(key)
    if val is None:
        return default
    return val.strip().lower() in ('1', 'true', 'yes', 'on')


# Detect whether we run inside the Replit dev environment. On Replit these
# variables are always present; on a self-hosted server (Hetzner) they are not.
_REPLIT_DETECTED = bool(
    os.environ.get('REPL_ID') or os.environ.get('REPLIT_DEV_DOMAIN')
)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
# Steerable via the DEBUG env var. Defaults to True so the Replit dev workflow
# (runserver serving static files) keeps working unchanged. Production sets
# DEBUG=False in its .env.
DEBUG = _env_bool('DEBUG', default=True)

# SECURITY WARNING: keep the secret key used in production secret!
# Read from the environment. In production (DEBUG=False) SECRET_KEY MUST be set
# explicitly — we never silently fall back to a random key there, because that
# would invalidate every session on each restart. In dev a per-process random
# key is fine.
SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = get_random_secret_key()
    else:
        raise ImproperlyConfigured(
            "SECRET_KEY must be set as an environment variable when DEBUG=False."
        )

# ALLOWED_HOSTS — fully env-driven (comma-separated). The fixed Hetzner server
# IP is ALWAYS accepted, so the box stays reachable directly even before a
# domain exists; the final domain is just added to the ALLOWED_HOSTS env var
# later — no code change required. Without an explicit list we fall back to '*'
# ONLY inside Replit dev (rotating iframe hostnames); a self-hosted production
# box defaults to the server IP instead of the unsafe wildcard.
HETZNER_SERVER_IP = '49.13.5.151'
_allowed_hosts = os.environ.get('ALLOWED_HOSTS')
if _allowed_hosts:
    ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts.split(',') if h.strip()]
elif _REPLIT_DETECTED or DEBUG:
    ALLOWED_HOSTS = ['*']
else:
    ALLOWED_HOSTS = [HETZNER_SERVER_IP]
# Guarantee the server IP is valid even when the env var only lists a domain.
if '*' not in ALLOWED_HOSTS and HETZNER_SERVER_IP not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(HETZNER_SERVER_IP)

# Base trusted origins for the Replit dev environment. Production hosts can be
# appended via the CSRF_TRUSTED_ORIGINS env var (comma-separated, full scheme).
CSRF_TRUSTED_ORIGINS = [
    'https://*.replit.dev',
    'https://*.repl.co',
    'http://localhost:5000',
    'http://0.0.0.0:5000',
    # Fixed Hetzner server IP so direct-IP access works out of the box (HTTP
    # today, HTTPS once TLS is active). The domain is appended via the env var.
    f'http://{HETZNER_SERVER_IP}',
    f'https://{HETZNER_SERVER_IP}',
]
_extra_csrf = os.environ.get('CSRF_TRUSTED_ORIGINS')
if _extra_csrf:
    CSRF_TRUSTED_ORIGINS += [
        o.strip() for o in _extra_csrf.split(',') if o.strip()
    ]

# Cookie security. Replit runs over HTTPS inside an iframe and therefore needs
# Secure cookies with SameSite=None. A plain-HTTP production deploy (V1, before
# HTTPS) must NOT use Secure cookies or the browser will drop them and login
# breaks. Steer via COOKIE_SECURE (default True keeps Replit dev intact).
COOKIE_SECURE = _env_bool('COOKIE_SECURE', default=True)
if COOKIE_SECURE:
    SESSION_COOKIE_SAMESITE = 'None'
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SAMESITE = 'None'
    CSRF_COOKIE_SECURE = True
else:
    SESSION_COOKIE_SAMESITE = 'Lax'
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SAMESITE = 'Lax'
    CSRF_COOKIE_SECURE = False
X_FRAME_OPTIONS = 'SAMEORIGIN'

# Full HTTPS hardening — only on a real TLS deploy (Hetzner behind nginx +
# Let's Encrypt). Kept OFF in Replit dev: the dev proxy is HTTPS, but runserver
# must not force SSL redirects or send HSTS (that would interfere with the dev
# iframe). Enable ENABLE_HTTPS=True in the production .env once certificates are
# active (and also COOKIE_SECURE=True for Secure cookies).
ENABLE_HTTPS = _env_bool('ENABLE_HTTPS', default=False)
if ENABLE_HTTPS:
    # nginx terminates TLS and forwards the original scheme in this header, so
    # Django correctly treats proxied requests as secure (no redirect loops).
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    
    'game',
]
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'game.middleware.LastSeenMiddleware',
]

LOGIN_URL = '/auth/login/'
LOGIN_REDIRECT_URL = '/'

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'game.context_processors.current_manager',
                'game.context_processors.posthog_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

import dj_database_url

_db_url = os.environ.get('DATABASE_URL')
if _db_url:
    DATABASES = {
        'default': dj_database_url.parse(_db_url, conn_max_age=600)
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'de'

TIME_ZONE = 'Europe/Berlin'

USE_I18N = True

USE_TZ = True

THOUSAND_SEPARATOR = '.'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
# STATIC_ROOT is where `collectstatic` gathers files for production serving
# (nginx). Harmless in Replit dev where runserver serves from app dirs.
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Basis-URL für Bild-Assets (Spielergesichter, Club-Logos, Trophäen …).
# Lokal/Replit: /static/assets/ (Ordner game/static/assets/).
# Live (Hetzner): ASSETS_BASE_URL=/assets/ — nginx serviert /var/www/assets.
ASSETS_BASE_URL = os.environ.get('ASSETS_BASE_URL', '/static/assets/')

# Dateisystem-Pfad für Asset-Uploads (Creator-Mode schreibt hierhin).
# Lokal/Replit: <BASE_DIR>/game/static/assets/
# Live (Hetzner): ASSETS_ROOT=/var/www/assets
ASSETS_ROOT = os.environ.get('ASSETS_ROOT', str(BASE_DIR / 'game' / 'static' / 'assets'))

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Media storage backend. Replit dev uses the Object Storage bucket; a
# self-hosted deploy uses the local filesystem (MEDIA_ROOT, served by nginx
# in production). Steer via REPLIT_OBJECT_STORAGE; defaults to on only when the
# Replit environment is detected, so Hetzner falls back to the filesystem.
USE_REPLIT_OBJECT_STORAGE = _env_bool(
    'REPLIT_OBJECT_STORAGE', default=_REPLIT_DETECTED
)
if USE_REPLIT_OBJECT_STORAGE:
    _default_storage = {
        "BACKEND": "game.object_storage_backend.ReplitObjectStorage",
    }
else:
    _default_storage = {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    }

STORAGES = {
    "default": _default_storage,
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

API_FOOTBALL_KEY = os.environ.get('API_FOOTBALL_KEY', '')

# ─── Sentry (Error-Monitoring) ────────────────────────────────────────────────
# DSN wird nach dem OAuth-Setup von Replit als SENTRY_DSN injiziert.
# Nur aktiv wenn DSN vorhanden → kein Einfluss auf lokale Dev-Loops ohne DSN.
_SENTRY_DSN = os.environ.get('SENTRY_DSN', '')
if _SENTRY_DSN:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration
    from sentry_sdk.integrations.celery import CeleryIntegration
    sentry_sdk.init(
        dsn=_SENTRY_DSN,
        integrations=[DjangoIntegration(), CeleryIntegration()],
        traces_sample_rate=1.0,
        send_default_pii=True,
        environment='development' if DEBUG else 'production',
    )

# ─── PostHog (User-Analytics) ─────────────────────────────────────────────────
# API-Key + Host werden nach dem OAuth-Setup von Replit injiziert.
# Der JS-Snippet in base.html liest diese Werte via Template-Tag.
POSTHOG_API_KEY = os.environ.get('POSTHOG_API_KEY', '')
POSTHOG_HOST    = os.environ.get('POSTHOG_HOST', 'https://eu.i.posthog.com')


# Celery / Hintergrund-Jobs
# https://docs.celeryq.dev/en/stable/django/first-steps-with-django.html
#
# Broker und Result-Backend laufen über denselben Redis wie der restliche
# Stack. REDIS_URL zeigt im Compose-Stack auf den Service "redis"; lokal
# (Replit dev) kann es per Env überschrieben werden (z. B. localhost).
CELERY_BROKER_URL = os.environ.get('REDIS_URL', 'redis://redis:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', CELERY_BROKER_URL)

# Zeitzone für Beat-Zeitpläne (deckungsgleich mit Django).
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = True

# Robustheit:
#  - Tasks erst nach erfolgreichem Lauf bestätigen (überlebt Worker-Neustart).
#  - Broker-Verbindung beim Start abwarten (Worker kommt mit dem Stack hoch).
#  - Laufzeit begrenzen und Worker-Kinder regelmäßig recyceln (gegen Leaks).
CELERY_TASK_ACKS_LATE = True
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_TASK_TIME_LIMIT = 30 * 60          # harte Obergrenze: 30 min
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60     # vorher SoftTimeLimitExceeded
CELERY_WORKER_MAX_TASKS_PER_CHILD = 200
CELERY_RESULT_EXPIRES = 60 * 60 * 24      # Ergebnisse 24 h aufbewahren

# Beat-Zeitplan: wiederkehrende Jobs. Intervall (Sekunden) per Env steuerbar,
# Standard täglich. Der Job führt ein bestehendes Management-Command über den
# generischen Task game.tasks.run_management_command aus.
_CITY_PIN_CHECK_INTERVAL = float(
    os.environ.get('CELERY_CITY_PIN_CHECK_INTERVAL', 24 * 60 * 60)
)
CELERY_BEAT_SCHEDULE = {
    'city-pin-check-taeglich': {
        'task': 'game.tasks.run_management_command',
        'schedule': _CITY_PIN_CHECK_INTERVAL,
        'args': ('check_city_pins',),
    },
}
