"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from django.core.management.utils import get_random_secret_key

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _env_bool(key, default=False):
    """Parse a truthy environment flag (1/true/yes/on)."""
    val = os.environ.get(key)
    if val is None:
        return default
    return val.strip().lower() in ('1', 'true', 'yes', 'on')


# Detect whether we run inside the Replit dev environment. On Replit these
# variables are always present; on a self-hosted server (Hetzner) they are not.
_REPLIT_DETECTED = bool(
    os.environ.get('REPL_ID') or os.environ.get('REPLIT_DEV_DOMAIN')
)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
# Steerable via the DEBUG env var. Defaults to True so the Replit dev workflow
# (runserver serving static files) keeps working unchanged. Production sets
# DEBUG=False in its .env.
DEBUG = _env_bool('DEBUG', default=True)

# SECURITY WARNING: keep the secret key used in production secret!
# Read from the environment. In production (DEBUG=False) SECRET_KEY MUST be set
# explicitly — we never silently fall back to a random key there, because that
# would invalidate every session on each restart. In dev a per-process random
# key is fine.
SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = get_random_secret_key()
    else:
        raise ImproperlyConfigured(
            "SECRET_KEY must be set as an environment variable when DEBUG=False."
        )

# ALLOWED_HOSTS — comma-separated env var. Defaults to '*' so Replit dev keeps
# working; production should pin it to the server IP / domain in its .env.
_allowed_hosts = os.environ.get('ALLOWED_HOSTS')
if _allowed_hosts:
    ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts.split(',') if h.strip()]
else:
    ALLOWED_HOSTS = ['*']

# Base trusted origins for the Replit dev environment. Production hosts can be
# appended via the CSRF_TRUSTED_ORIGINS env var (comma-separated, full scheme).
CSRF_TRUSTED_ORIGINS = [
    'https://*.replit.dev',
    'https://*.repl.co',
    'http://localhost:5000',
    'http://0.0.0.0:5000',
]
_extra_csrf = os.environ.get('CSRF_TRUSTED_ORIGINS')
if _extra_csrf:
    CSRF_TRUSTED_ORIGINS += [
        o.strip() for o in _extra_csrf.split(',') if o.strip()
    ]

# Cookie security. Replit runs over HTTPS inside an iframe and therefore needs
# Secure cookies with SameSite=None. A plain-HTTP production deploy (V1, before
# HTTPS) must NOT use Secure cookies or the browser will drop them and login
# breaks. Steer via COOKIE_SECURE (default True keeps Replit dev intact).
COOKIE_SECURE = _env_bool('COOKIE_SECURE', default=True)
if COOKIE_SECURE:
    SESSION_COOKIE_SAMESITE = 'None'
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SAMESITE = 'None'
    CSRF_COOKIE_SECURE = True
else:
    SESSION_COOKIE_SAMESITE = 'Lax'
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SAMESITE = 'Lax'
    CSRF_COOKIE_SECURE = False
X_FRAME_OPTIONS = 'SAMEORIGIN'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    
    'game',
]
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

LOGIN_URL = '/auth/login/'
LOGIN_REDIRECT_URL = '/'

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'game.context_processors.current_manager',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

import dj_database_url

_db_url = os.environ.get('DATABASE_URL')
if _db_url:
    DATABASES = {
        'default': dj_database_url.parse(_db_url, conn_max_age=600)
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'de'

TIME_ZONE = 'Europe/Berlin'

USE_I18N = True

USE_TZ = True

THOUSAND_SEPARATOR = '.'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
# STATIC_ROOT is where `collectstatic` gathers files for production serving
# (nginx). Harmless in Replit dev where runserver serves from app dirs.
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Media storage backend. Replit dev uses the Object Storage bucket; a
# self-hosted deploy uses the local filesystem (MEDIA_ROOT, served by nginx
# in production). Steer via REPLIT_OBJECT_STORAGE; defaults to on only when the
# Replit environment is detected, so Hetzner falls back to the filesystem.
USE_REPLIT_OBJECT_STORAGE = _env_bool(
    'REPLIT_OBJECT_STORAGE', default=_REPLIT_DETECTED
)
if USE_REPLIT_OBJECT_STORAGE:
    _default_storage = {
        "BACKEND": "game.object_storage_backend.ReplitObjectStorage",
    }
else:
    _default_storage = {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    }

STORAGES = {
    "default": _default_storage,
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

API_FOOTBALL_KEY = os.environ.get('API_FOOTBALL_KEY', '')
