# Generated by Django 6.0.5 on 2026-05-09 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='budget',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='player',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='market_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('TW', 'Torwart'), ('IV', 'Innenverteidiger'), ('LV', 'Linksverteidiger'), ('RV', 'Rechtsverteidiger'), ('ZDM', 'Zentrales Defensives Mittelfeld'), ('ZM', 'Zentrales Mittelfeld'), ('ZOM', 'Zentrales Offensives Mittelfeld'), ('LF', 'Linker Flügel'), ('RF', 'Rechter Flügel'), ('ST', 'Stürmer')], max_length=10),
        ),
        migrations.AlterField(
            model_name='player',
            name='potential',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='strength',
            field=models.IntegerField(default=50),
        ),
        migrations.CreateModel(
            name='PlayerStrengthProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_strength', models.IntegerField(default=50)),
                ('form_modifier', models.IntegerField(default=0)),
                ('final_strength', models.IntegerField(default=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='strength_profile', to='game.player')),
            ],
        ),
    ]
