# Generated by Django 6.0.5 on 2026-05-09 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_club_budget_alter_player_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='strength',
        ),
    ]
