# Generated by Django 6.0.5 on 2026-05-10 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_remove_player_strength'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='fm_inside_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='player',
            name='fm_inside_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
