# Generated by Django 6.0.5 on 2026-05-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_club_fm_inside_id_player_fm_inside_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='contract_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='market_value_note',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='player',
            name='source_positions',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='player',
            name='weekly_wage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
