# Generated by Django 6.0.5 on 2026-05-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_player_contract_until_player_market_value_note_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='market_value_note',
        ),
        migrations.RemoveField(
            model_name='player',
            name='weekly_wage',
        ),
        migrations.AddField(
            model_name='player',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='nationalities',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='player',
            name='primary_position',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='player',
            name='salary_per_match',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='player',
            name='transfermarkt_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='player',
            name='transfermarkt_market_value_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='player',
            name='transfermarkt_profile_url',
            field=models.URLField(blank=True),
        ),
    ]
