# Generated by Django 6.0.5 on 2026-05-11 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_remove_player_market_value_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('TW', 'Torwart'), ('IV', 'Innenverteidiger'), ('LV', 'Linksverteidiger'), ('RV', 'Rechtsverteidiger'), ('ZDM', 'Zentrales Defensives Mittelfeld'), ('ZM', 'Zentrales Mittelfeld'), ('ZOM', 'Zentrales Offensives Mittelfeld'), ('LF', 'Linker FlÃ¼gel'), ('RF', 'Rechter FlÃ¼gel'), ('ST', 'StÃ¼rmer')], max_length=10),
        ),
    ]
