# Generated by Django 6.0.5 on 2026-05-11 12:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_alter_player_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerSourceRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('EA', 'EA / SoFIFA / FIFAIndex'), ('FM', 'FMInside')], max_length=20)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('potential', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('source_url', models.URLField(blank=True)),
                ('source_version', models.CharField(blank=True, max_length=100)),
                ('checked_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_ratings', to='game.player')),
            ],
            options={
                'ordering': ['player__last_name', 'player__first_name', 'source'],
                'constraints': [models.UniqueConstraint(fields=('player', 'source'), name='unique_player_source_rating')],
            },
        ),
    ]
