# Generated by Django 6.0.5 on 2026-05-11 12:33

from decimal import Decimal

from django.db import migrations, models


POSITION_MAP = {
    'GK': 'TW',
    'TW': 'TW',
    'DC': 'IV',
    'IV': 'IV',
    'DL': 'LV',
    'LV': 'LV',
    'DR': 'RV',
    'RV': 'RV',
    'WBL': 'LOV',
    'LOV': 'LOV',
    'WBR': 'ROV',
    'ROV': 'ROV',
    'ZDM': 'DM',
    'DM': 'DM',
    'MC': 'ZM',
    'ZM': 'ZM',
    'ML': 'LM',
    'LM': 'LM',
    'MR': 'RM',
    'RM': 'RM',
    'AML': 'LF',
    'LF': 'LF',
    'AMR': 'RF',
    'RF': 'RF',
    'AMC': 'OM',
    'ZOM': 'OM',
    'OM': 'OM',
    'ST': 'ST',
    'Torwart': 'TW',
    'Innenverteidiger': 'IV',
    'Linker Verteidiger': 'LV',
    'Rechter Verteidiger': 'RV',
    'Defensives Mittelfeld': 'DM',
    'Zentrales Mittelfeld': 'ZM',
    'Linkes Mittelfeld': 'LM',
    'Rechtes Mittelfeld': 'RM',
    'Offensives Mittelfeld': 'OM',
    'Linksaussen': 'LF',
    'Linksau\u00dfen': 'LF',
    'Rechtsaussen': 'RF',
    'Rechtsau\u00dfen': 'RF',
    'Haengende Spitze': 'ST',
    'H\u00e4ngende Spitze': 'ST',
    'Mittelstuermer': 'ST',
    'Mittelst\u00fcrmer': 'ST',
}


def normalize_position(value):
    if not value:
        return ''

    for raw_token in str(value).split(','):
        token = raw_token.strip()
        if token in POSITION_MAP:
            return POSITION_MAP[token]

    return ''


def normalize_positions_and_create_career_end(apps, schema_editor):
    League = apps.get_model('game', 'League')
    Club = apps.get_model('game', 'Club')
    Player = apps.get_model('game', 'Player')

    special_league, _ = League.objects.get_or_create(
        name='Sonderstatus',
        defaults={
            'country': 'System',
        },
    )
    Club.objects.get_or_create(
        name='Karrierende',
        defaults={
            'short_name': 'KARR',
            'founded_year': 0,
            'budget': Decimal('0.00'),
            'league': special_league,
        },
    )

    for player in Player.objects.all():
        normalized_position = normalize_position(player.position)
        normalized_primary = normalize_position(player.primary_position)
        normalized_source = normalize_position(player.source_positions)

        changed_fields = []

        if normalized_position and player.position != normalized_position:
            player.position = normalized_position
            changed_fields.append('position')

        if player.primary_position != normalized_primary:
            player.primary_position = normalized_primary
            changed_fields.append('primary_position')

        if player.source_positions != normalized_source:
            player.source_positions = normalized_source
            changed_fields.append('source_positions')

        if changed_fields:
            player.save(update_fields=changed_fields)


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_playersourcerating'),
    ]

    operations = [
        migrations.RunPython(
            normalize_positions_and_create_career_end,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('TW', 'TW'), ('IV', 'IV'), ('LV', 'LV'), ('RV', 'RV'), ('LOV', 'LOV'), ('ROV', 'ROV'), ('DM', 'DM'), ('ZM', 'ZM'), ('LM', 'LM'), ('RM', 'RM'), ('LOM', 'LOM'), ('ROM', 'ROM'), ('OM', 'OM'), ('LF', 'LF'), ('RF', 'RF'), ('ST', 'ST')], max_length=10),
        ),
        migrations.AlterField(
            model_name='player',
            name='primary_position',
            field=models.CharField(blank=True, choices=[('TW', 'TW'), ('IV', 'IV'), ('LV', 'LV'), ('RV', 'RV'), ('LOV', 'LOV'), ('ROV', 'ROV'), ('DM', 'DM'), ('ZM', 'ZM'), ('LM', 'LM'), ('RM', 'RM'), ('LOM', 'LOM'), ('ROM', 'ROM'), ('OM', 'OM'), ('LF', 'LF'), ('RF', 'RF'), ('ST', 'ST')], max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='source_positions',
            field=models.CharField(blank=True, choices=[('TW', 'TW'), ('IV', 'IV'), ('LV', 'LV'), ('RV', 'RV'), ('LOV', 'LOV'), ('ROV', 'ROV'), ('DM', 'DM'), ('ZM', 'ZM'), ('LM', 'LM'), ('RM', 'RM'), ('LOM', 'LOM'), ('ROM', 'ROM'), ('OM', 'OM'), ('LF', 'LF'), ('RF', 'RF'), ('ST', 'ST')], max_length=100),
        ),
    ]
