# Generated by Django 6.0.5 on 2026-05-11 12:51

import django.db.models.deletion
from django.db import migrations, models


def populate_player_positions_and_real_life_club(apps, schema_editor):
    Player = apps.get_model('game', 'Player')

    for player in Player.objects.all():
        main_position = player.position or ''
        secondary_position = player.primary_position or ''

        if secondary_position == main_position:
            secondary_position = ''

        player.main_position_1 = main_position
        player.secondary_position_1 = secondary_position
        player.real_life_club_id = player.club_id
        player.save(
            update_fields=[
                'main_position_1',
                'secondary_position_1',
                'real_life_club',
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_alter_player_position_alter_player_primary_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='main_position_1',
            field=models.CharField(blank=True, choices=[('TW', 'TW'), ('IV', 'IV'), ('LV', 'LV'), ('RV', 'RV'), ('LOV', 'LOV'), ('ROV', 'ROV'), ('DM', 'DM'), ('ZM', 'ZM'), ('LM', 'LM'), ('RM', 'RM'), ('LOM', 'LOM'), ('ROM', 'ROM'), ('OM', 'OM'), ('LF', 'LF'), ('RF', 'RF'), ('ST', 'ST')], max_length=10, verbose_name='HP 1'),
        ),
        migrations.AddField(
            model_name='player',
            name='main_position_2',
            field=models.CharField(blank=True, choices=[('TW', 'TW'), ('IV', 'IV'), ('LV', 'LV'), ('RV', 'RV'), ('LOV', 'LOV'), ('ROV', 'ROV'), ('DM', 'DM'), ('ZM', 'ZM'), ('LM', 'LM'), ('RM', 'RM'), ('LOM', 'LOM'), ('ROM', 'ROM'), ('OM', 'OM'), ('LF', 'LF'), ('RF', 'RF'), ('ST', 'ST')], max_length=10, verbose_name='HP 2'),
        ),
        migrations.AddField(
            model_name='player',
            name='main_position_3',
            field=models.CharField(blank=True, choices=[('TW', 'TW'), ('IV', 'IV'), ('LV', 'LV'), ('RV', 'RV'), ('LOV', 'LOV'), ('ROV', 'ROV'), ('DM', 'DM'), ('ZM', 'ZM'), ('LM', 'LM'), ('RM', 'RM'), ('LOM', 'LOM'), ('ROM', 'ROM'), ('OM', 'OM'), ('LF', 'LF'), ('RF', 'RF'), ('ST', 'ST')], max_length=10, verbose_name='HP 3'),
        ),
        migrations.AddField(
            model_name='player',
            name='real_life_club',
            field=models.ForeignKey(blank=True, help_text='Aktueller realer Verein, getrennt vom Websoccer-Verein.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='real_life_players', to='game.club'),
        ),
        migrations.AddField(
            model_name='player',
            name='secondary_position_1',
            field=models.CharField(blank=True, choices=[('TW', 'TW'), ('IV', 'IV'), ('LV', 'LV'), ('RV', 'RV'), ('LOV', 'LOV'), ('ROV', 'ROV'), ('DM', 'DM'), ('ZM', 'ZM'), ('LM', 'LM'), ('RM', 'RM'), ('LOM', 'LOM'), ('ROM', 'ROM'), ('OM', 'OM'), ('LF', 'LF'), ('RF', 'RF'), ('ST', 'ST')], max_length=10, verbose_name='NP 1'),
        ),
        migrations.AddField(
            model_name='player',
            name='secondary_position_2',
            field=models.CharField(blank=True, choices=[('TW', 'TW'), ('IV', 'IV'), ('LV', 'LV'), ('RV', 'RV'), ('LOV', 'LOV'), ('ROV', 'ROV'), ('DM', 'DM'), ('ZM', 'ZM'), ('LM', 'LM'), ('RM', 'RM'), ('LOM', 'LOM'), ('ROM', 'ROM'), ('OM', 'OM'), ('LF', 'LF'), ('RF', 'RF'), ('ST', 'ST')], max_length=10, verbose_name='NP 2'),
        ),
        migrations.AddField(
            model_name='player',
            name='secondary_position_3',
            field=models.CharField(blank=True, choices=[('TW', 'TW'), ('IV', 'IV'), ('LV', 'LV'), ('RV', 'RV'), ('LOV', 'LOV'), ('ROV', 'ROV'), ('DM', 'DM'), ('ZM', 'ZM'), ('LM', 'LM'), ('RM', 'RM'), ('LOM', 'LOM'), ('ROM', 'ROM'), ('OM', 'OM'), ('LF', 'LF'), ('RF', 'RF'), ('ST', 'ST')], max_length=10, verbose_name='NP 3'),
        ),
        migrations.AddField(
            model_name='player',
            name='ws_injury_days_remaining',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='ws_injury_type',
            field=models.CharField(blank=True, help_text='Nur Websoccer-Verletzung, z. B. Muskelverletzung.', max_length=120),
        ),
        migrations.AddField(
            model_name='player',
            name='ws_suspension_matches_remaining',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='ws_suspension_reason',
            field=models.CharField(blank=True, help_text='Nur Websoccer-Sperre, z. B. Rotsperre.', max_length=120),
        ),
        migrations.RunPython(
            populate_player_positions_and_real_life_club,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(blank=True, choices=[('TW', 'TW'), ('IV', 'IV'), ('LV', 'LV'), ('RV', 'RV'), ('LOV', 'LOV'), ('ROV', 'ROV'), ('DM', 'DM'), ('ZM', 'ZM'), ('LM', 'LM'), ('RM', 'RM'), ('LOM', 'LOM'), ('ROM', 'ROM'), ('OM', 'OM'), ('LF', 'LF'), ('RF', 'RF'), ('ST', 'ST')], max_length=10),
        ),
    ]
