# Generated by Django 6.0.5 on 2026-05-11 14:35

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_player_main_position_1_player_main_position_2_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerDataReview',
            fields=[
            ],
            options={
                'verbose_name': 'Spieler-Datenpruefung',
                'verbose_name_plural': 'Spieler-Datenpruefung',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('game.player',),
        ),
        migrations.AddField(
            model_name='league',
            name='coefficient_source',
            field=models.CharField(blank=True, help_text='z. B. UEFA association coefficient oder interne Einstufung.', max_length=100),
        ),
        migrations.AddField(
            model_name='league',
            name='strength_coefficient',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Liga-Koeffizient fuer Form- und Leistungsgewichtung.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='playerstrengthprofile',
            name='base_strength',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=6),
        ),
        migrations.AlterField(
            model_name='playerstrengthprofile',
            name='final_strength',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=6),
        ),
        migrations.AlterField(
            model_name='playerstrengthprofile',
            name='form_modifier',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
        migrations.CreateModel(
            name='PlayerEditRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(choices=[('nationalities', 'Nationalitaet'), ('real_life_club', 'RL-Verein'), ('market_value', 'Marktwert'), ('main_positions', 'Hauptpositionen'), ('secondary_positions', 'Nebenpositionen'), ('source_rating', 'Source Rating'), ('default_base', 'Default-Basisstaerke')], max_length=40)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('requester_name', models.CharField(blank=True, max_length=120)),
                ('requester_note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Offen'), ('accepted', 'Angenommen'), ('rejected', 'Abgelehnt')], default='open', max_length=20)),
                ('decision_note', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_player_edit_requests', to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_requests', to='game.player')),
            ],
            options={
                'verbose_name': 'Spielerbearbeitungsantrag',
                'verbose_name_plural': 'Spielerbearbeitungsantraege',
                'ordering': ['status', '-created_at'],
            },
        ),
    ]
