# Generated by Django 6.0.5 on 2026-05-11 16:23

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def seed_api_football_reference_ids(apps, schema_editor):
    League = apps.get_model('game', 'League')
    Club = apps.get_model('game', 'Club')
    Player = apps.get_model('game', 'Player')

    League.objects.filter(name='1. Bundesliga').update(api_football_id=78)
    Club.objects.filter(fm_inside_id=915).update(api_football_id=157)
    Player.objects.filter(transfermarkt_id=132098).update(api_football_id=184)


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_playerdatareview_league_coefficient_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='api_football_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='league',
            name='api_football_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='player',
            name='api_football_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='PlayerFormSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('api_football', 'API-Football')], default='api_football', max_length=40)),
                ('fixture_id', models.PositiveIntegerField()),
                ('fixture_date', models.DateField()),
                ('league_api_football_id', models.PositiveIntegerField(blank=True, null=True)),
                ('team_api_football_id', models.PositiveIntegerField(blank=True, null=True)),
                ('team_name', models.CharField(blank=True, max_length=120)),
                ('opponent_name', models.CharField(blank=True, max_length=120)),
                ('minutes_played', models.PositiveSmallIntegerField(default=0)),
                ('possible_minutes', models.PositiveSmallIntegerField(default=90)),
                ('minutes_quote', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('started', models.BooleanField(default=False)),
                ('substituted_in', models.BooleanField(default=False)),
                ('captain', models.BooleanField(default=False)),
                ('position', models.CharField(blank=True, max_length=10)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('goals', models.PositiveSmallIntegerField(default=0)),
                ('assists', models.PositiveSmallIntegerField(default=0)),
                ('yellow_cards', models.PositiveSmallIntegerField(default=0)),
                ('red_cards', models.PositiveSmallIntegerField(default=0)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_snapshots', to='game.player')),
            ],
            options={
                'ordering': ['-fixture_date', '-fixture_id'],
                'constraints': [models.UniqueConstraint(fields=('player', 'source', 'fixture_id'), name='unique_player_form_snapshot_source_fixture')],
            },
        ),
        migrations.RunPython(
            seed_api_football_reference_ids,
            migrations.RunPython.noop,
        ),
    ]
