# Generated by Django 6.0.5 on 2026-05-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_club_api_football_id_league_api_football_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerformsnapshot',
            name='fixture_id',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='playerformsnapshot',
            name='source',
            field=models.CharField(choices=[('api_football', 'API-Football'), ('sportdb_flashscore', 'SportDB / Flashscore')], default='api_football', max_length=40),
        ),
    ]
