# Generated by Django 6.0.5 on 2026-05-11 19:27

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def seed_strength_modifier_settings(apps, schema_editor):
    StrengthFormulaSettings = apps.get_model('game', 'StrengthFormulaSettings')
    StrengthModifierRule = apps.get_model('game', 'StrengthModifierRule')

    settings, _created = StrengthFormulaSettings.objects.get_or_create(
        name='Standard',
        defaults={
            'is_active': True,
            'rating_modifier_factor': Decimal('5.00'),
            'default_league_median_rating': Decimal('6.80'),
            'default_freshness': Decimal('100.00'),
            'notes': (
                'Aktueller Arbeitsstand: keine Softcap, RL-Form aus Minutenquote '
                'und Rating gegen Liga-Median, Frische als Punktabzug.'
            ),
        },
    )

    rules = [
        ('minutes', '90-100 %', Decimal('90.00'), Decimal('100.00'), Decimal('4.00'), '', 10),
        ('minutes', '75-89 %', Decimal('75.00'), Decimal('89.99'), Decimal('2.50'), '', 20),
        ('minutes', '60-74 %', Decimal('60.00'), Decimal('74.99'), Decimal('1.00'), '', 30),
        ('minutes', '40-59 %', Decimal('40.00'), Decimal('59.99'), Decimal('-1.00'), '', 40),
        ('minutes', '20-39 %', Decimal('20.00'), Decimal('39.99'), Decimal('-3.00'), '', 50),
        ('minutes', '5-19 %', Decimal('5.00'), Decimal('19.99'), Decimal('-6.00'), '', 60),
        ('minutes', '0-4 %', Decimal('0.00'), Decimal('4.99'), Decimal('-8.00'), '', 70),
        ('freshness', '90-100', Decimal('90.00'), Decimal('100.00'), Decimal('0.00'), 'kein Risiko', 110),
        ('freshness', '85-89', Decimal('85.00'), Decimal('89.99'), Decimal('-0.50'), 'kein Risiko', 120),
        ('freshness', '80-84', Decimal('80.00'), Decimal('84.99'), Decimal('-1.00'), 'kein Risiko', 130),
        ('freshness', '75-79', Decimal('75.00'), Decimal('79.99'), Decimal('-1.50'), 'leichtes Risiko', 140),
        ('freshness', '70-74', Decimal('70.00'), Decimal('74.99'), Decimal('-2.00'), 'erhoehtes Risiko', 150),
        ('freshness', '65-69', Decimal('65.00'), Decimal('69.99'), Decimal('-3.00'), 'spuerbares Risiko', 160),
        ('freshness', '60-64', Decimal('60.00'), Decimal('64.99'), Decimal('-4.00'), 'hohes Risiko', 170),
        ('freshness', 'unter 60', Decimal('0.00'), Decimal('59.99'), Decimal('-6.00'), 'deutliches Risiko', 180),
    ]

    for category, label, min_value, max_value, modifier, risk_label, sort_order in rules:
        StrengthModifierRule.objects.get_or_create(
            settings=settings,
            category=category,
            label=label,
            defaults={
                'min_value': min_value,
                'max_value': max_value,
                'modifier': modifier,
                'risk_label': risk_label,
                'sort_order': sort_order,
                'is_active': True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_alter_playerformsnapshot_fixture_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrengthFormulaSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Standard', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('rating_modifier_factor', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Faktor fuer (Spieler-Rating - Liga-Medianrating).', max_digits=5)),
                ('default_league_median_rating', models.DecimalField(decimal_places=2, default=Decimal('6.80'), help_text='Fallback, bis der Median dynamisch aus Massendaten berechnet wird.', max_digits=4)),
                ('default_freshness', models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Wird genutzt, wenn noch kein Spieler-Frischewert gepflegt ist.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('notes', models.TextField(blank=True, help_text='Balancing-Notizen, z. B. Peak-Verteilung oder offene Tests.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Spielstaerke-Modifikator',
                'verbose_name_plural': 'Spielstaerke-Modifikatoren',
            },
        ),
        migrations.AddField(
            model_name='playerstrengthprofile',
            name='freshness',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Aktuelle Websoccer-Frische. Wirkt als Punktabzug, nicht als Multiplikator.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
        migrations.CreateModel(
            name='StrengthModifierRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('minutes', 'Minutenquote'), ('freshness', 'Frische')], max_length=20)),
                ('label', models.CharField(max_length=100)),
                ('min_value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('max_value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('modifier', models.DecimalField(decimal_places=2, help_text='Staerkepunkte. Bei Frische sind Abzuege negativ.', max_digits=6)),
                ('risk_label', models.CharField(blank=True, help_text='Nur fuer Frische relevant, z. B. leichtes Risiko.', max_length=80)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifier_rules', to='game.strengthformulasettings')),
            ],
            options={
                'verbose_name': 'Spielstaerke-Regel',
                'verbose_name_plural': 'Spielstaerke-Regeln',
                'ordering': ['category', 'sort_order', '-min_value'],
            },
        ),
        migrations.RunPython(
            seed_strength_modifier_settings,
            migrations.RunPython.noop,
        ),
    ]
