# Generated by Django 6.0.5 on 2026-05-11 20:37

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


def seed_data_sources_and_existing_ids(apps, schema_editor):
    DataSource = apps.get_model('game', 'DataSource')
    Player = apps.get_model('game', 'Player')
    PlayerExternalId = apps.get_model('game', 'PlayerExternalId')

    sources = {
        'TM': {
            'name': 'Transfermarkt',
            'base_url': 'https://www.transfermarkt.de/',
        },
        'FM': {
            'name': 'FMInside',
            'base_url': 'https://fminside.net/',
        },
        'SOFIFA': {
            'name': 'SoFIFA',
            'base_url': 'https://sofifa.com/',
        },
        'API_FOOTBALL': {
            'name': 'API-Football',
            'base_url': 'https://www.api-football.com/',
        },
        'WSC': {
            'name': 'Websoccer',
            'base_url': '',
        },
    }

    source_objects = {}
    for code, defaults in sources.items():
        source_objects[code], _created = DataSource.objects.get_or_create(
            code=code,
            defaults=defaults,
        )

    for player in Player.objects.all().order_by('id'):
        if not player.wsc_player_id:
            player.wsc_player_id = f'WSC-{player.id}'
            player.save(update_fields=['wsc_player_id'])

        PlayerExternalId.objects.get_or_create(
            player=player,
            source=source_objects['WSC'],
            defaults={
                'external_id': player.wsc_player_id,
                'is_primary': True,
            },
        )

        if player.transfermarkt_id:
            PlayerExternalId.objects.get_or_create(
                player=player,
                source=source_objects['TM'],
                defaults={
                    'external_id': str(player.transfermarkt_id),
                    'profile_url': player.transfermarkt_profile_url,
                },
            )

        if player.fm_inside_id:
            PlayerExternalId.objects.get_or_create(
                player=player,
                source=source_objects['FM'],
                defaults={
                    'external_id': str(player.fm_inside_id),
                },
            )

        if player.api_football_id:
            PlayerExternalId.objects.get_or_create(
                player=player,
                source=source_objects['API_FOOTBALL'],
                defaults={
                    'external_id': str(player.api_football_id),
                },
            )


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_strengthformulasettings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('TM', 'Transfermarkt'), ('FM', 'FMInside'), ('SOFIFA', 'SoFIFA'), ('API_FOOTBALL', 'API-Football'), ('WSC', 'Websoccer')], max_length=40, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('base_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Datenquelle',
                'verbose_name_plural': 'Datenquellen',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='player',
            name='wsc_player_id',
            field=models.CharField(blank=True, help_text='Stabile Websoccer-ID fuer Assets, Graphen und externe Zuordnung.', max_length=40, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='PlayerExternalId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=120)),
                ('profile_url', models.URLField(blank=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_ids', to='game.player')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_external_ids', to='game.datasource')),
            ],
            options={
                'verbose_name': 'Spieler-ID',
                'verbose_name_plural': 'Spieler-IDs',
                'ordering': ['player__last_name', 'player__first_name', 'source__name'],
                'constraints': [models.UniqueConstraint(fields=('source', 'external_id'), name='unique_external_player_id_per_source'), models.UniqueConstraint(fields=('player', 'source'), name='unique_player_external_id_per_source')],
            },
        ),
        migrations.CreateModel(
            name='PlayerMarketValueSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateField(default=django.utils.timezone.localdate)),
                ('value_eur', models.DecimalField(decimal_places=2, max_digits=15)),
                ('profile_url', models.URLField(blank=True)),
                ('source_version', models.CharField(blank=True, max_length=100)),
                ('update_current', models.BooleanField(default=True, help_text='Aktualisiert Player.market_value und salary_per_match beim Speichern.')),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_value_snapshots', to='game.player')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_value_snapshots', to='game.datasource')),
            ],
            options={
                'verbose_name': 'Marktwert-Snapshot',
                'verbose_name_plural': 'Marktwert-Snapshots',
                'ordering': ['-recorded_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('player', 'source', 'recorded_at'), name='unique_player_market_value_snapshot')],
            },
        ),
        migrations.CreateModel(
            name='PlayerSourceRatingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateField(default=django.utils.timezone.localdate)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('potential', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('source_url', models.URLField(blank=True)),
                ('source_version', models.CharField(blank=True, max_length=100)),
                ('update_current', models.BooleanField(default=True, help_text='Aktualisiert PlayerSourceRating fuer die aktuelle Staerkeberechnung.')),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_rating_snapshots', to='game.player')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_rating_snapshots', to='game.datasource')),
            ],
            options={
                'verbose_name': 'Source-Rating-Snapshot',
                'verbose_name_plural': 'Source-Rating-Snapshots',
                'ordering': ['-recorded_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('player', 'source', 'recorded_at'), name='unique_player_source_rating_snapshot')],
            },
        ),
        migrations.CreateModel(
            name='PlayerStrengthSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateField(default=django.utils.timezone.localdate)),
                ('match_reference', models.CharField(blank=True, max_length=120)),
                ('base_strength', models.DecimalField(decimal_places=2, max_digits=6)),
                ('final_strength', models.DecimalField(decimal_places=2, max_digits=6)),
                ('max_strength', models.DecimalField(decimal_places=2, max_digits=6)),
                ('last_10_average_strength', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('freshness', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('form_modifier', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strength_snapshots', to='game.player')),
            ],
            options={
                'verbose_name': 'Staerke-Snapshot',
                'verbose_name_plural': 'Staerke-Snapshots',
                'ordering': ['-recorded_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('player', 'recorded_at', 'match_reference'), name='unique_player_strength_snapshot')],
            },
        ),
        migrations.RunPython(
            seed_data_sources_and_existing_ids,
            migrations.RunPython.noop,
        ),
    ]
