# Generated by Django 6.0.5 on 2026-05-11 20:56

from decimal import Decimal

from django.db import migrations
from django.utils import timezone


def seed_player_history_snapshots(apps, schema_editor):
    DataSource = apps.get_model('game', 'DataSource')
    Player = apps.get_model('game', 'Player')
    PlayerMarketValueSnapshot = apps.get_model('game', 'PlayerMarketValueSnapshot')
    PlayerSourceRating = apps.get_model('game', 'PlayerSourceRating')
    PlayerSourceRatingSnapshot = apps.get_model('game', 'PlayerSourceRatingSnapshot')
    PlayerStrengthProfile = apps.get_model('game', 'PlayerStrengthProfile')
    PlayerStrengthSnapshot = apps.get_model('game', 'PlayerStrengthSnapshot')

    today = timezone.localdate()
    tm_source = DataSource.objects.get(code='TM')
    fm_source = DataSource.objects.get(code='FM')
    sofifa_source = DataSource.objects.get(code='SOFIFA')

    rating_sources = {
        'FM': fm_source,
        'EA': sofifa_source,
    }

    for player in Player.objects.all().order_by('id'):
        if player.market_value and player.market_value > 0:
            PlayerMarketValueSnapshot.objects.get_or_create(
                player=player,
                source=tm_source,
                recorded_at=today,
                defaults={
                    'value_eur': player.market_value,
                    'profile_url': player.transfermarkt_profile_url,
                    'source_version': f'Transfermarkt {today.isoformat()}',
                    'update_current': False,
                    'notes': 'Initial aus aktuellem Spieler-Marktwert uebernommen.',
                },
            )

        for rating in PlayerSourceRating.objects.filter(player=player):
            source = rating_sources.get(rating.source)
            if not source:
                continue

            PlayerSourceRatingSnapshot.objects.get_or_create(
                player=player,
                source=source,
                recorded_at=rating.checked_at or today,
                defaults={
                    'rating': rating.rating,
                    'potential': rating.potential,
                    'source_url': rating.source_url,
                    'source_version': rating.source_version,
                    'update_current': False,
                    'notes': rating.notes or 'Initial aus aktuellem Source-Rating uebernommen.',
                },
            )

        profile = PlayerStrengthProfile.objects.filter(player=player).first()
        if profile:
            source_potentials = [
                rating.potential
                for rating in PlayerSourceRating.objects.filter(player=player)
                if rating.potential is not None
            ]
            max_strength = (
                sum(source_potentials)
                if source_potentials
                else profile.final_strength
            )
            PlayerStrengthSnapshot.objects.get_or_create(
                player=player,
                recorded_at=today,
                match_reference='INITIAL',
                defaults={
                    'base_strength': profile.base_strength,
                    'final_strength': profile.final_strength,
                    'max_strength': max_strength,
                    'last_10_average_strength': profile.final_strength,
                    'freshness': getattr(profile, 'freshness', None),
                    'form_modifier': profile.form_modifier or Decimal('0.00'),
                    'notes': 'Initial aus aktuellem Staerkeprofil uebernommen.',
                },
            )


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_datasource_player_wsc_player_id_playerexternalid_and_more'),
    ]

    operations = [
        migrations.RunPython(
            seed_player_history_snapshots,
            migrations.RunPython.noop,
        ),
    ]
