# Generated by Django 6.0.5 on 2026-05-11 21:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_seed_player_history_snapshots'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerWeightedRatingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('api_football', 'API-Football'), ('sportdb_flashscore', 'SportDB / Flashscore')], default='sportdb_flashscore', max_length=40)),
                ('recorded_at', models.DateField(default=django.utils.timezone.localdate)),
                ('fixture_reference', models.CharField(blank=True, max_length=120)),
                ('weighted_rating', models.DecimalField(decimal_places=2, max_digits=4)),
                ('rating_minutes', models.PositiveSmallIntegerField(default=0)),
                ('match_count', models.PositiveSmallIntegerField(default=0)),
                ('window_label', models.CharField(default='Letzte 10 Spiele', max_length=80)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weighted_rating_snapshots', to='game.player')),
            ],
            options={
                'verbose_name': 'Gewichteter Rating-Snapshot',
                'verbose_name_plural': 'Gewichtete Rating-Snapshots',
                'ordering': ['-recorded_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('player', 'source', 'recorded_at', 'fixture_reference'), name='unique_player_weighted_rating_snapshot')],
            },
        ),
    ]
