# Generated by Django 6.0.5 on 2026-05-11 21:04

from decimal import Decimal

from django.db import migrations


def seed_weighted_rating_snapshots(apps, schema_editor):
    Player = apps.get_model('game', 'Player')
    PlayerFormSnapshot = apps.get_model('game', 'PlayerFormSnapshot')
    PlayerWeightedRatingSnapshot = apps.get_model(
        'game',
        'PlayerWeightedRatingSnapshot',
    )

    for player in Player.objects.all().order_by('id'):
        for source in ['sportdb_flashscore', 'api_football']:
            snapshots = list(
                PlayerFormSnapshot.objects.filter(
                    player=player,
                    source=source,
                    rating__isnull=False,
                    minutes_played__gt=0,
                ).order_by('fixture_date', 'id')
            )
            if not snapshots:
                continue

            for snapshot in snapshots[-10:]:
                window = [
                    candidate
                    for candidate in snapshots
                    if (
                        candidate.fixture_date < snapshot.fixture_date
                        or (
                            candidate.fixture_date == snapshot.fixture_date
                            and candidate.id <= snapshot.id
                        )
                    )
                ][-10:]
                rating_minutes = sum(item.minutes_played for item in window)
                if not rating_minutes:
                    continue

                weighted_rating = (
                    sum(item.rating * item.minutes_played for item in window) /
                    Decimal(rating_minutes)
                ).quantize(Decimal('0.01'))

                PlayerWeightedRatingSnapshot.objects.get_or_create(
                    player=player,
                    source=source,
                    recorded_at=snapshot.fixture_date,
                    fixture_reference=snapshot.fixture_id,
                    defaults={
                        'weighted_rating': weighted_rating,
                        'rating_minutes': rating_minutes,
                        'match_count': len(window),
                        'window_label': 'Letzte 10 Spiele',
                        'notes': 'Initial aus Spielrating und Einsatzminuten berechnet.',
                    },
                )


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_playerweightedratingsnapshot'),
    ]

    operations = [
        migrations.RunPython(
            seed_weighted_rating_snapshots,
            migrations.RunPython.noop,
        ),
    ]
