# Generated by Django 6.0.5 on 2026-05-11 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_seed_weighted_rating_snapshots'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='portrait_asset',
            field=models.CharField(blank=True, help_text='Optionaler Static-Pfad, z. B. game/images/players/123.svg. Leer nutzt automatisch die FMI-ID oder das Defaultbild.', max_length=255, verbose_name='Spielerbild'),
        ),
    ]
