# Generated by Django 6.0.5 on 2026-05-11 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_player_portrait_asset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='portrait_asset',
        ),
    ]
