# Generated by Codex on 2026-05-12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_remove_player_portrait_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='height_cm',
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text='Koerpergroesse in Zentimetern.',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='player',
            name='strong_foot',
            field=models.CharField(
                blank=True,
                choices=[
                    ('left', 'Links'),
                    ('right', 'Rechts'),
                    ('both', 'Beidfuss'),
                ],
                help_text='Staerkerer Fuss des Spielers.',
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name='PlayerAwardTitle',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('title', models.CharField(max_length=120)),
                ('season', models.CharField(blank=True, max_length=20)),
                ('competition', models.CharField(blank=True, max_length=120)),
                (
                    'trophy_asset_id',
                    models.CharField(
                        blank=True,
                        help_text='Dateiname oder ID aus Images/Trophies ohne Dateiendung.',
                        max_length=80,
                    ),
                ),
                ('count', models.PositiveSmallIntegerField(default=1)),
                ('awarded_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                (
                    'player',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='ws_awards_titles',
                        to='game.player',
                    ),
                ),
            ],
            options={
                'verbose_name': 'WS-Auszeichnung/Titel',
                'verbose_name_plural': 'WS-Auszeichnungen/Titel',
                'ordering': ['-awarded_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PlayerInjuryRecord',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'start_date',
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ('end_date', models.DateField(blank=True, null=True)),
                ('injury_type', models.CharField(max_length=120)),
                ('days_missed', models.PositiveSmallIntegerField(default=0)),
                ('competition', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                (
                    'player',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='ws_injury_records',
                        to='game.player',
                    ),
                ),
            ],
            options={
                'verbose_name': 'WS-Verletzung',
                'verbose_name_plural': 'WS-Verletzungen',
                'ordering': ['-start_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PlayerSeasonStat',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('season', models.CharField(default='2026/27', max_length=20)),
                ('competition', models.CharField(default='Liga', max_length=120)),
                ('matches', models.PositiveSmallIntegerField(default=0)),
                ('goals', models.PositiveSmallIntegerField(default=0)),
                ('assists', models.PositiveSmallIntegerField(default=0)),
                ('yellow_cards', models.PositiveSmallIntegerField(default=0)),
                ('red_cards', models.PositiveSmallIntegerField(default=0)),
                ('minutes_played', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'player',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='ws_season_stats',
                        to='game.player',
                    ),
                ),
            ],
            options={
                'verbose_name': 'WS-Saisonstatistik',
                'verbose_name_plural': 'WS-Saisonstatistiken',
                'ordering': ['-season', 'competition'],
            },
        ),
        migrations.CreateModel(
            name='PlayerSuspensionRecord',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'start_date',
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ('end_date', models.DateField(blank=True, null=True)),
                ('reason', models.CharField(max_length=120)),
                ('matches_missed', models.PositiveSmallIntegerField(default=0)),
                ('competition', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                (
                    'player',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='ws_suspension_records',
                        to='game.player',
                    ),
                ),
            ],
            options={
                'verbose_name': 'WS-Sperre',
                'verbose_name_plural': 'WS-Sperren',
                'ordering': ['-start_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PlayerTransferHistory',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'transfer_date',
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ('season', models.CharField(blank=True, max_length=20)),
                (
                    'fee_eur',
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                    ),
                ),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'from_club',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='outgoing_ws_transfers',
                        to='game.club',
                    ),
                ),
                (
                    'player',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='ws_transfer_history',
                        to='game.player',
                    ),
                ),
                (
                    'to_club',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='incoming_ws_transfers',
                        to='game.club',
                    ),
                ),
            ],
            options={
                'verbose_name': 'WS-Transfer',
                'verbose_name_plural': 'WS-Transfers',
                'ordering': ['-transfer_date', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='playerseasonstat',
            constraint=models.UniqueConstraint(
                fields=('player', 'season', 'competition'),
                name='unique_player_ws_season_stat',
            ),
        ),
    ]
