# Generated by Codex on 2026-05-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_player_profile_ws_dashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerseasonstat',
            name='average_grade',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='Websoccer-Note. 1.00 ist sehr gut, 6.00 schwach.',
                max_digits=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='playerseasonstat',
            name='season_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterModelOptions(
            name='playerseasonstat',
            options={
                'ordering': ['-season_number', 'competition'],
                'verbose_name': 'WS-Saisonstatistik',
                'verbose_name_plural': 'WS-Saisonstatistiken',
            },
        ),
    ]
