# Generated by Django 6.0.5 on 2026-05-17 23:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0024_playerseasonstat_player_of_match_awards'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubNewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('published_at', models.DateField(default=django.utils.timezone.localdate)),
                ('thumbnail_static_path', models.CharField(blank=True, max_length=240)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_news', to='game.club')),
            ],
            options={
                'verbose_name': 'Vereinsnews',
                'verbose_name_plural': 'Vereinsnews',
                'ordering': ['sort_order', '-published_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ClubPublicProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stadium_name', models.CharField(blank=True, max_length=120)),
                ('stadium_capacity', models.PositiveIntegerField(default=0)),
                ('average_attendance', models.PositiveIntegerField(default=0)),
                ('city_name', models.CharField(blank=True, max_length=120)),
                ('city_country', models.CharField(blank=True, max_length=100)),
                ('stadium_image_static_path', models.CharField(blank=True, max_length=240)),
                ('city_image_static_path', models.CharField(blank=True, max_length=240)),
                ('club', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='public_profile', to='game.club')),
                ('partner_club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partnered_public_profiles', to='game.club')),
            ],
            options={
                'verbose_name': 'Oeffentliches Vereinsprofil',
                'verbose_name_plural': 'Oeffentliche Vereinsprofile',
            },
        ),
        migrations.CreateModel(
            name='ClubTrophy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition_name', models.CharField(max_length=120)),
                ('count', models.PositiveSmallIntegerField(default=1)),
                ('trophy_asset_id', models.CharField(blank=True, max_length=80)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_trophies', to='game.club')),
            ],
            options={
                'verbose_name': 'Vereinstitel',
                'verbose_name_plural': 'Vereinstitel',
                'ordering': ['sort_order', 'competition_name'],
            },
        ),
        migrations.CreateModel(
            name='ClubProfileMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('next', 'Naechstes Spiel'), ('last', 'Letztes Spiel')], max_length=12)),
                ('competition_name', models.CharField(max_length=120)),
                ('matchday_label', models.CharField(max_length=80)),
                ('date_label', models.CharField(blank=True, max_length=80)),
                ('time_label', models.CharField(blank=True, max_length=40)),
                ('stadium_name', models.CharField(blank=True, max_length=120)),
                ('home_goals', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('away_goals', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('result_label', models.CharField(blank=True, choices=[('SIEG', 'Sieg'), ('UNENTSCHIEDEN', 'Unentschieden'), ('NIEDERLAGE', 'Niederlage')], max_length=20)),
                ('scorers', models.JSONField(blank=True, default=list)),
                ('away_club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='away_public_profile_matches', to='game.club')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_profile_matches', to='game.club')),
                ('home_club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_public_profile_matches', to='game.club')),
            ],
            options={
                'verbose_name': 'Vereinsprofil-Spiel',
                'verbose_name_plural': 'Vereinsprofil-Spiele',
                'ordering': ['kind', 'id'],
                'constraints': [models.UniqueConstraint(fields=('club', 'kind'), name='unique_club_public_profile_match_kind')],
            },
        ),
    ]
