# Generated by Django 6.0.5 on 2026-05-18 15:58

import django.db.models.deletion
import game.tactics
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0027_clear_seeded_partner_clubs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='main_position_1',
            field=models.CharField(blank=True, choices=[('TW', 'TW'), ('IV', 'IV'), ('LI', 'LI'), ('LV', 'LV'), ('RV', 'RV'), ('LOV', 'LOV'), ('ROV', 'ROV'), ('DM', 'DM'), ('ZM', 'ZM'), ('LM', 'LM'), ('RM', 'RM'), ('LOM', 'LOM'), ('ROM', 'ROM'), ('OM', 'OM'), ('LF', 'LF'), ('RF', 'RF'), ('ST', 'ST')], max_length=10, verbose_name='HP 1'),
        ),
        migrations.AlterField(
            model_name='player',
            name='main_position_2',
            field=models.CharField(blank=True, choices=[('TW', 'TW'), ('IV', 'IV'), ('LI', 'LI'), ('LV', 'LV'), ('RV', 'RV'), ('LOV', 'LOV'), ('ROV', 'ROV'), ('DM', 'DM'), ('ZM', 'ZM'), ('LM', 'LM'), ('RM', 'RM'), ('LOM', 'LOM'), ('ROM', 'ROM'), ('OM', 'OM'), ('LF', 'LF'), ('RF', 'RF'), ('ST', 'ST')], max_length=10, verbose_name='HP 2'),
        ),
        migrations.AlterField(
            model_name='player',
            name='main_position_3',
            field=models.CharField(blank=True, choices=[('TW', 'TW'), ('IV', 'IV'), ('LI', 'LI'), ('LV', 'LV'), ('RV', 'RV'), ('LOV', 'LOV'), ('ROV', 'ROV'), ('DM', 'DM'), ('ZM', 'ZM'), ('LM', 'LM'), ('RM', 'RM'), ('LOM', 'LOM'), ('ROM', 'ROM'), ('OM', 'OM'), ('LF', 'LF'), ('RF', 'RF'), ('ST', 'ST')], max_length=10, verbose_name='HP 3'),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(blank=True, choices=[('TW', 'TW'), ('IV', 'IV'), ('LI', 'LI'), ('LV', 'LV'), ('RV', 'RV'), ('LOV', 'LOV'), ('ROV', 'ROV'), ('DM', 'DM'), ('ZM', 'ZM'), ('LM', 'LM'), ('RM', 'RM'), ('LOM', 'LOM'), ('ROM', 'ROM'), ('OM', 'OM'), ('LF', 'LF'), ('RF', 'RF'), ('ST', 'ST')], max_length=10),
        ),
        migrations.AlterField(
            model_name='player',
            name='primary_position',
            field=models.CharField(blank=True, choices=[('TW', 'TW'), ('IV', 'IV'), ('LI', 'LI'), ('LV', 'LV'), ('RV', 'RV'), ('LOV', 'LOV'), ('ROV', 'ROV'), ('DM', 'DM'), ('ZM', 'ZM'), ('LM', 'LM'), ('RM', 'RM'), ('LOM', 'LOM'), ('ROM', 'ROM'), ('OM', 'OM'), ('LF', 'LF'), ('RF', 'RF'), ('ST', 'ST')], max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='secondary_position_1',
            field=models.CharField(blank=True, choices=[('TW', 'TW'), ('IV', 'IV'), ('LI', 'LI'), ('LV', 'LV'), ('RV', 'RV'), ('LOV', 'LOV'), ('ROV', 'ROV'), ('DM', 'DM'), ('ZM', 'ZM'), ('LM', 'LM'), ('RM', 'RM'), ('LOM', 'LOM'), ('ROM', 'ROM'), ('OM', 'OM'), ('LF', 'LF'), ('RF', 'RF'), ('ST', 'ST')], max_length=10, verbose_name='NP 1'),
        ),
        migrations.AlterField(
            model_name='player',
            name='secondary_position_2',
            field=models.CharField(blank=True, choices=[('TW', 'TW'), ('IV', 'IV'), ('LI', 'LI'), ('LV', 'LV'), ('RV', 'RV'), ('LOV', 'LOV'), ('ROV', 'ROV'), ('DM', 'DM'), ('ZM', 'ZM'), ('LM', 'LM'), ('RM', 'RM'), ('LOM', 'LOM'), ('ROM', 'ROM'), ('OM', 'OM'), ('LF', 'LF'), ('RF', 'RF'), ('ST', 'ST')], max_length=10, verbose_name='NP 2'),
        ),
        migrations.AlterField(
            model_name='player',
            name='secondary_position_3',
            field=models.CharField(blank=True, choices=[('TW', 'TW'), ('IV', 'IV'), ('LI', 'LI'), ('LV', 'LV'), ('RV', 'RV'), ('LOV', 'LOV'), ('ROV', 'ROV'), ('DM', 'DM'), ('ZM', 'ZM'), ('LM', 'LM'), ('RM', 'RM'), ('LOM', 'LOM'), ('ROM', 'ROM'), ('OM', 'OM'), ('LF', 'LF'), ('RF', 'RF'), ('ST', 'ST')], max_length=10, verbose_name='NP 3'),
        ),
        migrations.AlterField(
            model_name='player',
            name='source_positions',
            field=models.CharField(blank=True, choices=[('TW', 'TW'), ('IV', 'IV'), ('LI', 'LI'), ('LV', 'LV'), ('RV', 'RV'), ('LOV', 'LOV'), ('ROV', 'ROV'), ('DM', 'DM'), ('ZM', 'ZM'), ('LM', 'LM'), ('RM', 'RM'), ('LOM', 'LOM'), ('ROM', 'ROM'), ('OM', 'OM'), ('LF', 'LF'), ('RF', 'RF'), ('ST', 'ST')], max_length=100),
        ),
        migrations.CreateModel(
            name='TacticSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('squad_scope', models.CharField(choices=[('pro', 'Profis'), ('youth', 'Jugend')], default='pro', max_length=12)),
                ('formation', models.JSONField(blank=True, default=game.tactics.default_formation)),
                ('lineup', models.JSONField(blank=True, default=game.tactics.default_lineup)),
                ('bench', models.JSONField(blank=True, default=game.tactics.default_bench)),
                ('standards', models.JSONField(blank=True, default=game.tactics.default_standards)),
                ('substitutions', models.JSONField(blank=True, default=game.tactics.default_substitutions)),
                ('first_half', models.JSONField(blank=True, default=game.tactics.default_half_tactic)),
                ('second_half', models.JSONField(blank=True, default=game.tactics.default_half_tactic)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tactic_setups', to='game.club')),
            ],
            options={
                'verbose_name': 'Taktik',
                'verbose_name_plural': 'Taktiken',
                'ordering': ['club__name', 'squad_scope'],
                'constraints': [models.UniqueConstraint(fields=('club', 'squad_scope'), name='unique_club_tactic_setup_scope')],
            },
        ),
        migrations.CreateModel(
            name='TacticTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('squad_scope', models.CharField(choices=[('pro', 'Profis'), ('youth', 'Jugend')], default='pro', max_length=12)),
                ('name', models.CharField(max_length=80)),
                ('formation', models.JSONField(blank=True, default=game.tactics.default_formation)),
                ('lineup', models.JSONField(blank=True, default=game.tactics.default_lineup)),
                ('bench', models.JSONField(blank=True, default=game.tactics.default_bench)),
                ('standards', models.JSONField(blank=True, default=game.tactics.default_standards)),
                ('substitutions', models.JSONField(blank=True, default=game.tactics.default_substitutions)),
                ('first_half', models.JSONField(blank=True, default=game.tactics.default_half_tactic)),
                ('second_half', models.JSONField(blank=True, default=game.tactics.default_half_tactic)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tactic_templates', to='game.club')),
            ],
            options={
                'verbose_name': 'Taktikvorlage',
                'verbose_name_plural': 'Taktikvorlagen',
                'ordering': ['club__name', 'squad_scope', 'name'],
                'constraints': [models.UniqueConstraint(fields=('club', 'squad_scope', 'name'), name='unique_club_tactic_template_scope_name')],
            },
        ),
    ]
