# Generated by Django 6.0.5 on 2026-05-20 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0028_alter_player_main_position_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='shirt_number',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Trikotnummer des Spielers.', null=True),
        ),
    ]
