# Generated by Django 6.0.5 on 2026-05-20 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0029_add_shirt_number_to_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='nt_nationality',
            field=models.CharField(blank=True, help_text='Die Nation, für die der Spieler international registriert ist. Wird für das NT-Badge auf dem Spielerprofil verwendet. Leer lassen, um automatisch die erste Nationalität zu verwenden.', max_length=60, verbose_name='Nationalmannschafts-Nation'),
        ),
    ]
