# Generated by Django 6.0.5 on 2026-06-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0031_add_nt_nationality_to_clubprofilematch'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('trainer_type', models.CharField(choices=[('laptoptrainer', 'Laptoptrainer'), ('taktikfuchs', 'Taktikfuchs'), ('motivator', 'Motivator'), ('talentschmied', 'Talentschmied'), ('transferstratege', 'Transferstratege'), ('pokaljager', 'Pokaljäger'), ('offensivarchitekt', 'Offensivarchitekt'), ('underdog', 'Underdog-Flüsterer'), ('aufstiegsheld', 'Aufstiegsheld'), ('defensivmeister', 'Defensivmeister'), ('weltenbummler', 'Weltenbummler'), ('serienmeister', 'Serienmeister'), ('feuerwehrmann', 'Feuerwehrmann'), ('vereinslegende', 'Vereinslegende')], default='laptoptrainer', max_length=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Manager-Profil',
                'verbose_name_plural': 'Manager-Profile',
            },
        ),
    ]
