# Generated by Django 6.0.5 on 2026-06-01 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0034_seed_club_trophies'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='managerprofile',
            name='highscore',
            field=models.CharField(blank=True, default='–', max_length=50),
        ),
        migrations.AddField(
            model_name='managerprofile',
            name='level',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='managerprofile',
            name='member_since',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managerprofile',
            name='nationality_flag',
            field=models.CharField(blank=True, default='game/images/flags/771.svg', max_length=200),
        ),
        migrations.AddField(
            model_name='managerprofile',
            name='nationality_name',
            field=models.CharField(blank=True, default='Deutschland', max_length=100),
        ),
        migrations.AddField(
            model_name='managerprofile',
            name='profile_image',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='managerprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='managerprofile',
            name='xp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='managerprofile',
            name='xp_max',
            field=models.PositiveIntegerField(default=15000),
        ),
    ]
