# Generated by Django 6.0.5 on 2026-06-01 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0047_seed_full_trophies_international_clubs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerprofile',
            name='nationality_flag',
            field=models.CharField(blank=True, default='https://flagcdn.com/de.svg', max_length=200),
        ),
    ]
