# Generated by Django 6.0.5 on 2026-06-02 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0056_clubpublicprofile_map_coords_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='managed_by',
            field=models.OneToOneField(blank=True, help_text='Welcher Manager leitet diesen Verein gerade? Bitte nicht direkt bearbeiten — stattdessen im Vereins-Admin "Trainer zuweisen" oder "Trainer entlassen" nutzen, damit die Karrierekarte automatisch aktualisiert wird.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_club', to='game.managerprofile', verbose_name='Aktueller Trainer'),
        ),
    ]
