# Generated by Django 6.0.5 on 2026-06-03 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0057_add_club_managed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='loan_partner_club',
            field=models.ForeignKey(blank=True, help_text='Der andere Verein des Leihgeschäfts (Stamm- bzw. Leihverein).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_partner_players', to='game.club'),
        ),
        migrations.AddField(
            model_name='player',
            name='loan_status',
            field=models.CharField(blank=True, choices=[('none', 'Kein Leihverhältnis'), ('loaned_in', 'Geliehen'), ('loaned_out', 'Verliehen')], default='none', help_text='Geliehen = im Verein aktiv, gehört einem anderen Verein. Verliehen = gehört diesem Verein, spielt aktuell woanders.', max_length=12, verbose_name='Leihstatus'),
        ),
        migrations.AddField(
            model_name='player',
            name='loan_until',
            field=models.DateField(blank=True, null=True, verbose_name='Leihe bis'),
        ),
    ]
