# Generated by Django 6.0.5 on 2026-06-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0059_seed_demo_loans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='main_position_1',
            field=models.CharField(blank=True, choices=[('TW', 'TW'), ('IV', 'IV'), ('LV', 'LV'), ('RV', 'RV'), ('LOV', 'LOV'), ('ROV', 'ROV'), ('DM', 'DM'), ('ZM', 'ZM'), ('LM', 'LM'), ('RM', 'RM'), ('LOM', 'LOM'), ('ROM', 'ROM'), ('OM', 'OM'), ('LF', 'LF'), ('RF', 'RF'), ('ST', 'ST')], max_length=10, verbose_name='HP 1'),
        ),
        migrations.AlterField(
            model_name='player',
            name='main_position_2',
            field=models.CharField(blank=True, choices=[('TW', 'TW'), ('IV', 'IV'), ('LV', 'LV'), ('RV', 'RV'), ('LOV', 'LOV'), ('ROV', 'ROV'), ('DM', 'DM'), ('ZM', 'ZM'), ('LM', 'LM'), ('RM', 'RM'), ('LOM', 'LOM'), ('ROM', 'ROM'), ('OM', 'OM'), ('LF', 'LF'), ('RF', 'RF'), ('ST', 'ST')], max_length=10, verbose_name='HP 2'),
        ),
        migrations.AlterField(
            model_name='player',
            name='main_position_3',
            field=models.CharField(blank=True, choices=[('TW', 'TW'), ('IV', 'IV'), ('LV', 'LV'), ('RV', 'RV'), ('LOV', 'LOV'), ('ROV', 'ROV'), ('DM', 'DM'), ('ZM', 'ZM'), ('LM', 'LM'), ('RM', 'RM'), ('LOM', 'LOM'), ('ROM', 'ROM'), ('OM', 'OM'), ('LF', 'LF'), ('RF', 'RF'), ('ST', 'ST')], max_length=10, verbose_name='HP 3'),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(blank=True, choices=[('TW', 'TW'), ('IV', 'IV'), ('LV', 'LV'), ('RV', 'RV'), ('LOV', 'LOV'), ('ROV', 'ROV'), ('DM', 'DM'), ('ZM', 'ZM'), ('LM', 'LM'), ('RM', 'RM'), ('LOM', 'LOM'), ('ROM', 'ROM'), ('OM', 'OM'), ('LF', 'LF'), ('RF', 'RF'), ('ST', 'ST')], max_length=10),
        ),
        migrations.AlterField(
            model_name='player',
            name='primary_position',
            field=models.CharField(blank=True, choices=[('TW', 'TW'), ('IV', 'IV'), ('LV', 'LV'), ('RV', 'RV'), ('LOV', 'LOV'), ('ROV', 'ROV'), ('DM', 'DM'), ('ZM', 'ZM'), ('LM', 'LM'), ('RM', 'RM'), ('LOM', 'LOM'), ('ROM', 'ROM'), ('OM', 'OM'), ('LF', 'LF'), ('RF', 'RF'), ('ST', 'ST')], max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='secondary_position_1',
            field=models.CharField(blank=True, choices=[('TW', 'TW'), ('IV', 'IV'), ('LV', 'LV'), ('RV', 'RV'), ('LOV', 'LOV'), ('ROV', 'ROV'), ('DM', 'DM'), ('ZM', 'ZM'), ('LM', 'LM'), ('RM', 'RM'), ('LOM', 'LOM'), ('ROM', 'ROM'), ('OM', 'OM'), ('LF', 'LF'), ('RF', 'RF'), ('ST', 'ST')], max_length=10, verbose_name='NP 1'),
        ),
        migrations.AlterField(
            model_name='player',
            name='secondary_position_2',
            field=models.CharField(blank=True, choices=[('TW', 'TW'), ('IV', 'IV'), ('LV', 'LV'), ('RV', 'RV'), ('LOV', 'LOV'), ('ROV', 'ROV'), ('DM', 'DM'), ('ZM', 'ZM'), ('LM', 'LM'), ('RM', 'RM'), ('LOM', 'LOM'), ('ROM', 'ROM'), ('OM', 'OM'), ('LF', 'LF'), ('RF', 'RF'), ('ST', 'ST')], max_length=10, verbose_name='NP 2'),
        ),
        migrations.AlterField(
            model_name='player',
            name='secondary_position_3',
            field=models.CharField(blank=True, choices=[('TW', 'TW'), ('IV', 'IV'), ('LV', 'LV'), ('RV', 'RV'), ('LOV', 'LOV'), ('ROV', 'ROV'), ('DM', 'DM'), ('ZM', 'ZM'), ('LM', 'LM'), ('RM', 'RM'), ('LOM', 'LOM'), ('ROM', 'ROM'), ('OM', 'OM'), ('LF', 'LF'), ('RF', 'RF'), ('ST', 'ST')], max_length=10, verbose_name='NP 3'),
        ),
        migrations.AlterField(
            model_name='player',
            name='source_positions',
            field=models.CharField(blank=True, choices=[('TW', 'TW'), ('IV', 'IV'), ('LV', 'LV'), ('RV', 'RV'), ('LOV', 'LOV'), ('ROV', 'ROV'), ('DM', 'DM'), ('ZM', 'ZM'), ('LM', 'LM'), ('RM', 'RM'), ('LOM', 'LOM'), ('ROM', 'ROM'), ('OM', 'OM'), ('LF', 'LF'), ('RF', 'RF'), ('ST', 'ST')], max_length=100),
        ),
    ]
