# Generated by Django 6.0.5 on 2026-06-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0060_remove_libero_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_on_loan_list',
            field=models.BooleanField(default=False, verbose_name='Auf Leihliste'),
        ),
        migrations.AddField(
            model_name='player',
            name='is_on_transfer_list',
            field=models.BooleanField(default=False, verbose_name='Auf Transferliste'),
        ),
    ]
