# Generated by Django 6.0.5 on 2026-06-04 16:20

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0061_player_transfer_loan_list_flags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=100)),
                ('lawn_quality', models.PositiveSmallIntegerField(default=85, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Rasenqualität (1–100)')),
                ('nord_standing', models.PositiveIntegerField(default=0, verbose_name='Nord – Stehplätze')),
                ('nord_seating', models.PositiveIntegerField(default=0, verbose_name='Nord – Sitzplätze')),
                ('nord_vip', models.PositiveIntegerField(default=0, verbose_name='Nord – VIP')),
                ('ost_standing', models.PositiveIntegerField(default=0, verbose_name='Ost – Stehplätze')),
                ('ost_seating', models.PositiveIntegerField(default=0, verbose_name='Ost – Sitzplätze')),
                ('ost_vip', models.PositiveIntegerField(default=0, verbose_name='Ost – VIP')),
                ('sued_standing', models.PositiveIntegerField(default=0, verbose_name='Süd – Stehplätze')),
                ('sued_seating', models.PositiveIntegerField(default=0, verbose_name='Süd – Sitzplätze')),
                ('sued_vip', models.PositiveIntegerField(default=0, verbose_name='Süd – VIP')),
                ('west_standing', models.PositiveIntegerField(default=0, verbose_name='West – Stehplätze')),
                ('west_seating', models.PositiveIntegerField(default=0, verbose_name='West – Sitzplätze')),
                ('west_vip', models.PositiveIntegerField(default=0, verbose_name='West – VIP')),
                ('price_standing', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=6, verbose_name='Ticketpreis Steh (€)')),
                ('price_seating', models.DecimalField(decimal_places=2, default=Decimal('35.00'), max_digits=6, verbose_name='Ticketpreis Sitz (€)')),
                ('price_vip', models.DecimalField(decimal_places=2, default=Decimal('120.00'), max_digits=6, verbose_name='Ticketpreis VIP (€)')),
                ('club', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stadium', to='game.club')),
            ],
            options={
                'verbose_name': 'Stadion',
                'verbose_name_plural': 'Stadien',
            },
        ),
    ]
