# Generated by Django 6.0.5 on 2026-06-04 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0064_seed_stadium_data_fix'),
    ]

    operations = [
        migrations.CreateModel(
            name='StadiumExpansion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stand', models.CharField(choices=[('NORD', 'Nordkurve'), ('OST', 'Osttribüne'), ('SUED', 'Südkurve'), ('WEST', 'Westtribüne')], max_length=4)),
                ('seat_type', models.CharField(choices=[('STEH', 'Stehplatz'), ('SITZ', 'Sitzplatz'), ('VIP', 'VIP')], max_length=4)),
                ('seats_added', models.PositiveIntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expansions', to='game.stadium')),
            ],
            options={
                'verbose_name': 'Stadionausbau',
                'verbose_name_plural': 'Stadionausbauten',
                'ordering': ['-ordered_at'],
            },
        ),
    ]
