# Generated by Django 6.0.5 on 2026-06-04 16:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0065_stadium_expansion'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='fan_popularity',
            field=models.PositiveSmallIntegerField(default=50, help_text='Wie beliebt ist der Verein bei Fans? Beeinflusst die Stadionauslastung.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Fanbeliebtheit (1–100)'),
        ),
        migrations.CreateModel(
            name='MatchdayRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_label', models.CharField(blank=True, max_length=200, verbose_name='Spielbezeichnung')),
                ('competition_name', models.CharField(blank=True, max_length=120, verbose_name='Wettbewerb')),
                ('auslastung_pct', models.DecimalField(decimal_places=1, help_text='Tatsächliche Auslastung dieses Spieltags in Prozent (0–100).', max_digits=5, verbose_name='Auslastung (%)')),
                ('attendance', models.PositiveIntegerField(default=0, verbose_name='Zuschauer')),
                ('revenue_standing', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Einnahmen Stehplätze (€)')),
                ('revenue_seating', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Einnahmen Sitzplätze (€)')),
                ('revenue_vip', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Einnahmen VIP (€)')),
                ('revenue_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Gesamteinnahmen (€)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Verbucht am')),
                ('match_result', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matchday_revenue', to='game.matchresult', verbose_name='Spielergebnis')),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_entries', to='game.stadium', verbose_name='Stadion')),
            ],
            options={
                'verbose_name': 'Spieltags-Einnahmen',
                'verbose_name_plural': 'Spieltags-Einnahmen',
                'ordering': ['-created_at'],
            },
        ),
    ]
