# Generated by Django 6.0.5 on 2026-06-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0066_matchday_revenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadium',
            name='medizin_level',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Medizin Stufe'),
        ),
        migrations.AddField(
            model_name='stadium',
            name='nlz_level',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='NLZ Stufe'),
        ),
        migrations.AddField(
            model_name='stadium',
            name='office_level',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Geschäftsstelle Stufe'),
        ),
        migrations.AddField(
            model_name='stadium',
            name='training_level',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Trainingsgelände Stufe'),
        ),
    ]
