# Generated by Django 6.0.5 on 2026-06-05 20:21

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0067_stadium_facility_levels'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoenessCoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hoeness_coins', to='game.managerprofile')),
            ],
            options={
                'verbose_name': 'Hoeneß-Coin-Guthaben',
                'verbose_name_plural': 'Hoeneß-Coin-Guthaben',
            },
        ),
        migrations.CreateModel(
            name='SeasonGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_number', models.PositiveSmallIntegerField(default=1)),
                ('goal_tier', models.CharField(choices=[('meister', 'Meister'), ('top4', 'Top 4'), ('international', 'Internationale Plätze'), ('mittelfeld', 'Gesichertes Mittelfeld'), ('klassenerhalt', 'Klassenerhalt')], max_length=20)),
                ('rank_in_league', models.PositiveSmallIntegerField(help_text='Kaderstärke-Rang innerhalb der Liga bei Zielverkündung.')),
                ('league_size', models.PositiveSmallIntegerField(default=0)),
                ('squad_strength', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Summe der Top-11 base_strength bei Zielverkündung.', max_digits=9)),
                ('required_max_rank', models.PositiveSmallIntegerField(default=0, help_text='Maximal erlaubter Endplatz, um das Ziel zu erfüllen.')),
                ('final_rank', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('achieved', models.BooleanField(blank=True, help_text='Leer = noch nicht ausgewertet, sonst erfüllt/verfehlt.', null=True)),
                ('declared_at', models.DateTimeField(auto_now_add=True)),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_goals', to='game.club')),
            ],
            options={
                'verbose_name': 'Saisonziel',
                'verbose_name_plural': 'Saisonziele',
                'ordering': ['-season_number', 'rank_in_league'],
                'constraints': [models.UniqueConstraint(fields=('club', 'season_number'), name='seasongoal_unique_club_season')],
            },
        ),
    ]
