# Generated by Django 6.0.5 on 2026-06-05 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0068_hoenesscoin_seasongoal'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSeasonState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_season', models.PositiveSmallIntegerField(default=0, help_text='Aktuelle Saisonnummer (beginnt bei 0).')),
                ('is_started', models.BooleanField(default=False, help_text='Erst wenn aktiv, verkündet der Präsident die Saisonziele.')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Saison-Status',
                'verbose_name_plural': 'Saison-Status',
            },
        ),
    ]
