# Generated by Django 6.0.5 on 2026-06-06 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0069_gameseasonstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.SmallIntegerField(help_text='Positiv = verdient, negativ = ausgegeben.')),
                ('reason', models.CharField(choices=[('win', 'Sieg'), ('big_win', 'Kantersieg'), ('season_goal', 'Saisonziel erfüllt'), ('boost_transfer', 'Transfermarkt-Boost'), ('scout_talent', 'Talentscout')], max_length=30)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_transactions', to='game.managerprofile')),
            ],
            options={
                'verbose_name': 'Coin-Transaktion',
                'verbose_name_plural': 'Coin-Transaktionen',
                'ordering': ['-created_at'],
            },
        ),
    ]
