# Generated by Django 6.0.5 on 2026-06-06 17:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0072_sportgericht_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manageratrisk',
            options={'verbose_name': 'Entlassungskandidat', 'verbose_name_plural': 'Entlassungskandidaten (Zufriedenheit 0 %)'},
        ),
        migrations.CreateModel(
            name='ClubFinancialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Datum')),
                ('season', models.CharField(blank=True, max_length=20, verbose_name='Saison')),
                ('category', models.CharField(choices=[('ticketverkauf', 'Ticketverkauf'), ('sponsor', 'Sponsoren'), ('tv_gelder', 'TV-Gelder'), ('transfer_einnahme', 'Transfer (Einnahme)'), ('leih_einnahme', 'Leiheinnahme'), ('praemie', 'Prämie'), ('sonstige_einnahme', 'Sonstige Einnahme'), ('transfer_ausgabe', 'Transfer (Ausgabe)'), ('profigehalt', 'Profigehalt'), ('jugendgehalt', 'Jugendgehalt'), ('stadionkosten', 'Stadionkosten'), ('stadionumfeld', 'Stadionumfeld'), ('sonstige_ausgabe', 'Sonstige Ausgabe')], max_length=30, verbose_name='Kategorie')),
                ('description', models.CharField(max_length=200, verbose_name='Verwendungszweck')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positiv = Einnahme, Negativ = Ausgabe.', max_digits=15, verbose_name='Betrag (€)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_transactions', to='game.club', verbose_name='Verein')),
            ],
            options={
                'verbose_name': 'Finanztransaktion',
                'verbose_name_plural': 'Finanztransaktionen',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClubSponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Sponsorname')),
                ('sponsor_type', models.CharField(choices=[('tv', 'TV-Vertrag'), ('trikot', 'Trikotsponsor'), ('haupt', 'Hauptsponsor'), ('ausrüster', 'Ausrüster'), ('sonstig', 'Sonstige Sponsoren')], max_length=20, verbose_name='Typ')),
                ('amount_per_season', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Betrag / Saison (€)')),
                ('season', models.CharField(blank=True, max_length=20, verbose_name='Saison')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsors', to='game.club', verbose_name='Verein')),
            ],
            options={
                'verbose_name': 'Vereinssponsor',
                'verbose_name_plural': 'Vereinssponsoren',
                'ordering': ['sponsor_type', 'name'],
            },
        ),
    ]
