# Generated by Django 6.0.5 on 2026-06-07 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0073_add_club_financial_transaction_and_sponsor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerCareerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateField(verbose_name='Amtsantritt')),
                ('ended_at', models.DateField(blank=True, null=True, verbose_name='Amtsende')),
                ('end_reason', models.CharField(blank=True, choices=[('resign', 'Rücktritt'), ('fired', 'Entlassung'), ('season_end', 'Saisonende'), ('mutual', 'Einvernehmliche Trennung')], max_length=20, null=True, verbose_name='Abgangsgrund')),
                ('active', models.BooleanField(default=True, help_text='Genau ein aktiver Eintrag pro Manager erlaubt (App-Ebene).', verbose_name='Aktiv')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_career_entries', to='game.club', verbose_name='Verein')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_entries', to='game.managerprofile', verbose_name='Manager')),
            ],
            options={
                'verbose_name': 'Manager-Karriereeintrag',
                'verbose_name_plural': 'Manager-Karriereeinträge',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['manager', 'active'], name='mgr_career_active_idx'), models.Index(fields=['club', 'active'], name='mgr_career_club_idx')],
            },
        ),
    ]
