# Generated by Django 6.0.5 on 2026-06-08 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0074_manager_career_entry'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='managercareerentry',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('manager',), name='one_active_entry_per_manager', violation_error_message='Dieser Manager hat bereits einen aktiven Verein.'),
        ),
        migrations.AddConstraint(
            model_name='managercareerentry',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('club',), name='one_active_entry_per_club', violation_error_message='Dieser Verein hat bereits einen aktiven Manager.'),
        ),
    ]
