# Generated by Django 6.0.6 on 2026-06-08 08:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0075_manager_career_entry_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='cl_spots',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Champions-League-Plätze'),
        ),
        migrations.AddField(
            model_name='league',
            name='conference_spots',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Conference-League-Plätze'),
        ),
        migrations.AddField(
            model_name='league',
            name='cup_winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cup_titles', to='game.club', verbose_name='Pokalsieger (aktuelle Saison)'),
        ),
        migrations.AddField(
            model_name='league',
            name='el_spots',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Europa-League-Plätze'),
        ),
        migrations.AddField(
            model_name='league',
            name='logo_static_path',
            field=models.CharField(blank=True, help_text='Statischer Pfad zum Liga-Logo, z. B. game/images/competitions/bundesliga.svg', max_length=240),
        ),
        migrations.AddField(
            model_name='league',
            name='relegation_spots',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='Abstiegsplätze'),
        ),
        migrations.AddField(
            model_name='league',
            name='season_winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='league_titles', to='game.club', verbose_name='Meister (aktuelle Saison)'),
        ),
        migrations.CreateModel(
            name='LeagueNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Titel')),
                ('published_at', models.DateField(default=django.utils.timezone.localdate, verbose_name='Veröffentlicht')),
                ('thumbnail_static_path', models.CharField(blank=True, max_length=240, verbose_name='Vorschaubild')),
                ('body', models.TextField(blank=True, verbose_name='Text')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_items', to='game.league', verbose_name='Liga')),
            ],
            options={
                'verbose_name': 'Liga-News',
                'verbose_name_plural': 'Liga-News',
                'ordering': ['sort_order', '-published_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SeasonFixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchday', models.PositiveSmallIntegerField(verbose_name='Spieltag')),
                ('scheduled_date', models.DateField(blank=True, null=True, verbose_name='Datum')),
                ('scheduled_time', models.TimeField(blank=True, null=True, verbose_name='Uhrzeit')),
                ('season', models.CharField(default='2025/26', max_length=20, verbose_name='Saison')),
                ('home_goals', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Heimtore')),
                ('away_goals', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Auswärtstore')),
                ('is_played', models.BooleanField(default=False, verbose_name='Gespielt')),
                ('home_lineup_set', models.BooleanField(default=False, verbose_name='Heimaufstellung steht')),
                ('away_lineup_set', models.BooleanField(default=False, verbose_name='Auswärtsaufstellung steht')),
                ('away_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_fixtures', to='game.club', verbose_name='Auswärtsverein')),
                ('home_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_fixtures', to='game.club', verbose_name='Heimverein')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixtures', to='game.league', verbose_name='Liga')),
            ],
            options={
                'verbose_name': 'Spielplan-Eintrag',
                'verbose_name_plural': 'Spielplan',
                'ordering': ['matchday', 'scheduled_date', 'scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='LeagueStandings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(default='2025/26', help_text='z. B. "2025/26"', max_length=20, verbose_name='Saison')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Platz')),
                ('position_change', models.SmallIntegerField(default=0, help_text='Positiv = aufgestiegen, negativ = abgestiegen, 0 = unverändert.', verbose_name='Platzierungsänderung')),
                ('played', models.PositiveSmallIntegerField(default=0, verbose_name='Spiele')),
                ('won', models.PositiveSmallIntegerField(default=0, verbose_name='Siege')),
                ('drawn', models.PositiveSmallIntegerField(default=0, verbose_name='Unentschieden')),
                ('lost', models.PositiveSmallIntegerField(default=0, verbose_name='Niederlagen')),
                ('goals_for', models.PositiveSmallIntegerField(default=0, verbose_name='Tore')),
                ('goals_against', models.PositiveSmallIntegerField(default=0, verbose_name='Gegentore')),
                ('points', models.SmallIntegerField(default=0, verbose_name='Punkte')),
                ('point_deduction', models.PositiveSmallIntegerField(default=0, help_text='Vom Admin vergebener Punktabzug (wird von Punkten abgezogen).', verbose_name='Punktabzug')),
                ('form', models.CharField(blank=True, default='', help_text='5-stelliger String aus W/D/L, neuestes Ergebnis zuerst. z.B. "WWDLW".', max_length=5, verbose_name='Form (letzte 5)')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_standings', to='game.club', verbose_name='Verein')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='game.league', verbose_name='Liga')),
            ],
            options={
                'verbose_name': 'Ligatabelle-Eintrag',
                'verbose_name_plural': 'Ligatabelle',
                'ordering': ['position', '-points', 'club__name'],
                'unique_together': {('league', 'club', 'season')},
            },
        ),
    ]
