# Generated by Django 6.0.6 on 2026-06-09 07:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0078_inactivityrecord_unique_per_matchday'),
    ]

    operations = [
        migrations.AddField(
            model_name='playersourcerating',
            name='abschluss',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AddField(
            model_name='playersourcerating',
            name='ausdauer',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AddField(
            model_name='playersourcerating',
            name='defensivstellung',
            field=models.PositiveSmallIntegerField(blank=True, help_text='FMI: Positioning (defensiv) / SoFIFA: Stellungsspiel.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AddField(
            model_name='playersourcerating',
            name='dribbling',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AddField(
            model_name='playersourcerating',
            name='ecken',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Nur FMInside.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AddField(
            model_name='playersourcerating',
            name='elfmeter',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AddField(
            model_name='playersourcerating',
            name='flanken',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AddField(
            model_name='playersourcerating',
            name='freistoss',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AddField(
            model_name='playersourcerating',
            name='kopfball',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AddField(
            model_name='playersourcerating',
            name='kraft',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AddField(
            model_name='playersourcerating',
            name='passspiel',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AddField(
            model_name='playersourcerating',
            name='teamwork',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Nur FMInside.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AddField(
            model_name='playersourcerating',
            name='technik',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Nur FMInside.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AddField(
            model_name='playersourcerating',
            name='tempo',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AddField(
            model_name='playersourcerating',
            name='tw_eins_gegen_eins',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Nur FMInside.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AddField(
            model_name='playersourcerating',
            name='tw_fangsicherheit',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AddField(
            model_name='playersourcerating',
            name='tw_passen',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AddField(
            model_name='playersourcerating',
            name='tw_reflexe',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AddField(
            model_name='playersourcerating',
            name='tw_stellungsspiel',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AddField(
            model_name='playersourcerating',
            name='uebersicht',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AddField(
            model_name='playersourcerating',
            name='zweikampf',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='leaguestandings',
            name='season',
            field=models.CharField(default='0', help_text='Numerische Saisonnummer als String (z. B. "0", "1", "2") – passend zu GameSeasonState.current_season.', max_length=20, verbose_name='Saison'),
        ),
        migrations.AlterField(
            model_name='seasonfixture',
            name='season',
            field=models.CharField(default='0', max_length=20, verbose_name='Saison'),
        ),
    ]
