# Generated by Django 6.0.6 on 2026-06-09 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0079_playersourcerating_abschluss_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='strong_foot',
            field=models.CharField(blank=True, choices=[('L', 'Links'), ('R', 'Rechts'), ('B', 'Beidfuss')], help_text='Staerkerer Fuss des Spielers.', max_length=10),
        ),
        migrations.CreateModel(
            name='PlayerEditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('profil', 'Profil'), ('verein', 'Verein & Vertrag'), ('position', 'Positionen'), ('source', 'Quelldaten'), ('staerke', 'Stärke'), ('bild', 'Bild'), ('verletzung', 'Verletzung / Sperre'), ('system', 'System')], max_length=20)),
                ('summary', models.TextField()),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_edit_logs', to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_logs', to='game.player')),
            ],
            options={
                'verbose_name': 'Spieler-Änderungslog',
                'verbose_name_plural': 'Spieler-Änderungslogs',
                'ordering': ['-changed_at'],
            },
        ),
    ]
