# Generated by Django 6.0.6 on 2026-06-09 10:24

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0080_player_edit_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerRLFormProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_football_player_id', models.IntegerField(blank=True, null=True)),
                ('api_football_team_id', models.PositiveIntegerField(blank=True, null=True)),
                ('api_football_team_name', models.CharField(blank=True, max_length=120)),
                ('api_football_season', models.PositiveSmallIntegerField(default=2024)),
                ('rl_form_score', models.SmallIntegerField(default=0)),
                ('rl_form_fit', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=4)),
                ('rl_form_avg_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('rl_form_minutes', models.IntegerField(default=0)),
                ('rl_form_minutes_share', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('rl_form_games_checked', models.SmallIntegerField(default=0)),
                ('rl_form_games_played', models.SmallIntegerField(default=0)),
                ('rl_form_status', models.CharField(choices=[('not_mapped', 'Kein Mapping'), ('not_fetched', 'Noch nicht abgerufen'), ('fetched', 'Abgerufen'), ('no_minutes', 'Keine Einsätze'), ('minutes_without_rating', 'Minuten ohne Note'), ('api_error', 'API-Fehler'), ('stale', 'Veraltet')], default='not_mapped', max_length=30)),
                ('rl_form_updated_at', models.DateTimeField(blank=True, null=True)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rl_form_profile', to='game.player')),
            ],
            options={
                'verbose_name': 'RL-Form-Profil',
                'verbose_name_plural': 'RL-Form-Profile',
            },
        ),
    ]
