# Generated by Django 6.0.6 on 2026-06-09 10:39

import game.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0081_player_rl_form_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerrlformprofile',
            name='api_football_season',
            field=models.PositiveSmallIntegerField(default=game.models._rl_form_season_default),
        ),
    ]
