# Generated by Django 6.0.6 on 2026-06-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0082_player_rl_form_season_callable_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiFootballDailyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('request_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'API-Football Tagesverbrauch',
                'verbose_name_plural': 'API-Football Tagesverbräuche',
                'ordering': ['-date'],
            },
        ),
    ]
