# Generated by Django 6.0.6 on 2026-06-09 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0083_api_football_daily_usage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceImportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('sofifa', 'SoFIFA')], default='sofifa', max_length=20)),
                ('version', models.CharField(blank=True, help_text='z. B. FC26_2025-09-19', max_length=100)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('dry_run', models.BooleanField(default=False)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('count_new', models.PositiveIntegerField(default=0)),
                ('count_updated', models.PositiveIntegerField(default=0)),
                ('count_unchanged', models.PositiveIntegerField(default=0)),
                ('count_unmatched', models.PositiveIntegerField(default=0)),
                ('count_error', models.PositiveIntegerField(default=0)),
                ('unmatched', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_import_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Import-Lauf',
                'verbose_name_plural': 'Import-Läufe',
                'ordering': ['-imported_at', '-id'],
            },
        ),
    ]
