# Generated by Django 6.0.6 on 2026-06-11 08:08

import game.tactics
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0085_remove_clubprofilematch'),
    ]

    operations = [
        migrations.AddField(
            model_name='tacticsetup',
            name='conditions',
            field=models.JSONField(blank=True, default=game.tactics.default_conditions),
        ),
        migrations.AddField(
            model_name='tacticsetup',
            name='instructions',
            field=models.JSONField(blank=True, default=game.tactics.default_instructions),
        ),
        migrations.AddField(
            model_name='tactictemplate',
            name='conditions',
            field=models.JSONField(blank=True, default=game.tactics.default_conditions),
        ),
        migrations.AddField(
            model_name='tactictemplate',
            name='instructions',
            field=models.JSONField(blank=True, default=game.tactics.default_instructions),
        ),
    ]
