# Generated by Django 6.0.6 on 2026-06-11 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0086_tacticsetup_conditions_tacticsetup_instructions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulatedMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_goals', models.PositiveSmallIntegerField(default=0)),
                ('away_goals', models.PositiveSmallIntegerField(default=0)),
                ('report_data', models.JSONField(default=dict, help_text='Vollständiger Spielbericht als JSON (Tore, Stats, Spieler).')),
                ('simulated_at', models.DateTimeField(auto_now_add=True)),
                ('away_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulated_away_matches', to='game.club')),
                ('home_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulated_home_matches', to='game.club')),
            ],
            options={
                'verbose_name': 'Simuliertes Spiel',
                'verbose_name_plural': 'Simulierte Spiele',
                'ordering': ['-simulated_at'],
            },
        ),
    ]
