# Generated by Django 6.0.6 on 2026-06-14 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0090_simulatedmatch_match_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerseasonstat',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ws_player_season_stats', to='game.club', verbose_name='Verein'),
        ),
        migrations.AddField(
            model_name='playerseasonstat',
            name='dismissals',
            field=models.PositiveSmallIntegerField(default=0, help_text='Summe aus Gelb-Rot- und Direktrot-Karten.', verbose_name='Platzverweise (GelbRot + DirektRot)'),
        ),
        migrations.AddField(
            model_name='playerseasonstat',
            name='rating_best',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Niedrigster Notenwert (1.0 = beste mögliche Note).', max_digits=3, null=True, verbose_name='Beste Note'),
        ),
        migrations.AddField(
            model_name='playerseasonstat',
            name='rating_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='Anzahl der gewerteten Einsätze (mit Note).', verbose_name='Noten-Anzahl'),
        ),
        migrations.AddField(
            model_name='playerseasonstat',
            name='rating_sum',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Summe aller Einzelnoten für Ø-Berechnung.', max_digits=8, null=True, verbose_name='Noten-Summe'),
        ),
        migrations.AddField(
            model_name='playerseasonstat',
            name='rating_worst',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Höchster Notenwert (6.0 = schlechteste mögliche Note).', max_digits=3, null=True, verbose_name='Schlechteste Note'),
        ),
        migrations.AddField(
            model_name='playerseasonstat',
            name='starts',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Startelf-Einsätze'),
        ),
        migrations.AlterField(
            model_name='playerseasonstat',
            name='average_grade',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Websoccer-Note (Durchschnitt). 1.00 ist sehr gut, 6.00 schwach.', max_digits=3, null=True),
        ),
    ]
