# Generated by Django 6.0.6 on 2026-06-14 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0091_playerseasonstat_noten_persistenz'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='competition_type',
            field=models.CharField(choices=[('league', 'Liga'), ('cup', 'Pokal')], default='league', max_length=10, verbose_name='Wettbewerbstyp'),
        ),
        migrations.AddField(
            model_name='league',
            name='max_teams',
            field=models.PositiveSmallIntegerField(default=18, help_text='Maximale Anzahl Vereine (Liga) bzw. Pokalteilnehmer.', verbose_name='Max. Teilnehmer'),
        ),
        migrations.AlterField(
            model_name='league',
            name='cup_winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cup_titles_legacy', to='game.club', verbose_name='Pokalsieger (Legacy — nicht mehr genutzt)'),
        ),
        migrations.CreateModel(
            name='CupSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=20, verbose_name='Saison')),
                ('status', models.CharField(choices=[('setup', 'Vorbereitung'), ('running', 'Laufend'), ('completed', 'Abgeschlossen')], default='setup', max_length=20, verbose_name='Status')),
                ('competition', models.ForeignKey(limit_choices_to={'competition_type': 'cup'}, on_delete=django.db.models.deletion.CASCADE, related_name='cup_seasons', to='game.league', verbose_name='Wettbewerb')),
                ('participants', models.ManyToManyField(blank=True, related_name='cup_participations', to='game.club', verbose_name='Teilnehmer (Snapshot)')),
                ('winner_club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cup_titles', to='game.club', verbose_name='Pokalsieger')),
            ],
            options={
                'verbose_name': 'Pokalsaison',
                'verbose_name_plural': 'Pokalsaisons',
                'ordering': ['-season', 'competition'],
            },
        ),
        migrations.CreateModel(
            name='CupRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveSmallIntegerField(verbose_name='Rundennummer')),
                ('round_code', models.CharField(help_text='z. B. round_of_32, round_of_16, quarter_final, semi_final, final', max_length=30, verbose_name='Rundencode')),
                ('status', models.CharField(choices=[('pending', 'Ausstehend'), ('scheduled', 'Angesetzt'), ('completed', 'Abgeschlossen')], default='pending', max_length=20, verbose_name='Status')),
                ('scheduled_date', models.DateField(blank=True, null=True, verbose_name='Spieltag')),
                ('cup_season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='game.cupseason', verbose_name='Pokalsaison')),
            ],
            options={
                'verbose_name': 'Pokalrunde',
                'verbose_name_plural': 'Pokalrunden',
                'ordering': ['cup_season', 'round_number'],
            },
        ),
        migrations.CreateModel(
            name='CupFixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bracket_position', models.PositiveSmallIntegerField(help_text='Aufsteigende Zahl pro Runde — bestimmt die Anzeigereihenfolge im Baum.', verbose_name='Bracket-Position')),
                ('is_bye', models.BooleanField(default=False, verbose_name='Freilos')),
                ('status', models.CharField(choices=[('scheduled', 'Angesetzt'), ('played', 'Gespielt'), ('bye', 'Freilos')], default='scheduled', max_length=20, verbose_name='Status')),
                ('home_goals_90', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Heimtore (90 min)')),
                ('away_goals_90', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Auswärtstore (90 min)')),
                ('home_goals_et', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Heimtore (Verl.)')),
                ('away_goals_et', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Auswärtstore (Verl.)')),
                ('home_penalties', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Heim-Elfmeter')),
                ('away_penalties', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Auswärts-Elfmeter')),
                ('decided_by', models.CharField(blank=True, choices=[('regular_time', 'Reguläre Spielzeit'), ('extra_time', 'Verlängerung'), ('penalties', 'Elfmeterschießen')], max_length=20, null=True, verbose_name='Entschieden durch')),
                ('away_club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cup_away_fixtures', to='game.club', verbose_name='Auswärtsverein')),
                ('home_club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cup_home_fixtures', to='game.club', verbose_name='Heimverein')),
                ('simulated_match', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cup_fixture', to='game.simulatedmatch', verbose_name='Spielbericht')),
                ('winner_club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cup_wins', to='game.club', verbose_name='Sieger')),
                ('cup_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixtures', to='game.cupround', verbose_name='Pokalrunde')),
            ],
            options={
                'verbose_name': 'Pokalbegegnung',
                'verbose_name_plural': 'Pokalbegegnungen',
                'ordering': ['cup_round', 'bracket_position'],
                'constraints': [models.UniqueConstraint(fields=('cup_round', 'bracket_position'), name='unique_cup_round_bracket_position')],
            },
        ),
        migrations.AddConstraint(
            model_name='cupseason',
            constraint=models.UniqueConstraint(fields=('competition', 'season'), name='unique_cup_competition_season'),
        ),
        migrations.AddConstraint(
            model_name='cupround',
            constraint=models.UniqueConstraint(fields=('cup_season', 'round_number'), name='unique_cup_round'),
        ),
    ]
