# Generated by Django 6.0.6 on 2026-06-16 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0093_club_job_availability_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='is_import_placeholder',
            field=models.BooleanField(default=False, help_text='Automatisch beim Spielerimport angelegter Minimal-Verein (realer Stammverein / Leihgeber). Ohne Liga, Stadion, Finanzen.', verbose_name='Platzhalterverein'),
        ),
        migrations.AddField(
            model_name='club',
            name='transfermarkt_id',
            field=models.PositiveBigIntegerField(blank=True, help_text='Transfermarkt-Vereins-ID. Eindeutige Erkennung beim Import.', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='club',
            name='transfermarkt_profile_url',
            field=models.URLField(blank=True, help_text='Kanonischer Transfermarkt-Vereinslink.'),
        ),
        migrations.AlterField(
            model_name='club',
            name='job_availability_type',
            field=models.CharField(choices=[('none', 'Nicht freigegeben'), ('free_pick', 'Free Pick'), ('normal', 'Normale Bewerbung'), ('top', 'Top-Bewerbung')], default='free_pick', help_text='Legt fest, ob und mit welcher Bewerbungsart der Verein auf der Job-Angebote-Liste erscheint. Wird vom Creator nach einer Trainer-Entlassung manuell gesetzt.', max_length=20, verbose_name='Job-Freigabe'),
        ),
        migrations.AlterField(
            model_name='player',
            name='market_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Marktwert in Euro. NULL bedeutet "unbekannt" — nie automatisch auf 0 setzen, da 0 ein echter Wert wäre.', max_digits=15, null=True),
        ),
        migrations.CreateModel(
            name='ClubPlayerImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tm_club_id', models.PositiveBigIntegerField(help_text='Transfermarkt-Vereins-ID der zu importierenden Kaderseite.')),
                ('tm_season_id', models.PositiveIntegerField(help_text='Bei Erstellung eingefrorene Transfermarkt-Saison-ID.')),
                ('season_label', models.CharField(help_text='Anzeige der Saison, z. B. "2025/26".', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Wartet auf lokalen Importer'), ('claimed', 'Vom lokalen Importer übernommen'), ('running', 'Import läuft'), ('review', 'Zur Kontrolle bereit'), ('importing', 'Datenbankimport läuft'), ('completed', 'Abgeschlossen'), ('failed', 'Fehlgeschlagen'), ('cancelled', 'Abgebrochen')], default='pending', max_length=20)),
                ('progress_current', models.PositiveIntegerField(default=0)),
                ('progress_total', models.PositiveIntegerField(default=0)),
                ('current_step', models.CharField(blank=True, max_length=200)),
                ('error_message', models.TextField(blank=True)),
                ('lease_token', models.CharField(blank=True, default='', help_text='Pro Claim zufällig erzeugtes Geheimnis; bindet einen Importer.', max_length=64)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='club_player_import_jobs', to=settings.AUTH_USER_MODEL)),
                ('ws_club', models.ForeignKey(help_text='Der bei Auftragserstellung gewählte WS-Verein.', on_delete=django.db.models.deletion.CASCADE, related_name='player_import_jobs', to='game.club')),
            ],
            options={
                'verbose_name': 'Spielerimport-Auftrag',
                'verbose_name_plural': 'Spielerimport-Aufträge',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlayerImportCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tm_player_id', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('new', 'Neuer Spieler'), ('existing_changed', 'Vorhanden — geändert'), ('existing_unchanged', 'Vorhanden — unverändert'), ('missing_fmi', 'FMInside fehlt'), ('missing_sofifa', 'SoFIFA fehlt'), ('ambiguous_fmi', 'FMInside mehrdeutig'), ('ambiguous_sofifa', 'SoFIFA mehrdeutig'), ('invalid', 'Ungültig'), ('source_error', 'Quellenfehler'), ('ready', 'Importbereit'), ('imported', 'Importiert'), ('skipped', 'Übersprungen')], default='new', max_length=20)),
                ('selected_for_import', models.BooleanField(default=False)),
                ('overwrite_existing', models.BooleanField(default=False)),
                ('tm_raw', models.JSONField(blank=True, default=dict)),
                ('position_raw', models.JSONField(blank=True, default=dict)),
                ('fmi_raw', models.JSONField(blank=True, default=dict)),
                ('sofifa_raw', models.JSONField(blank=True, default=dict)),
                ('normalized_data', models.JSONField(blank=True, default=dict)),
                ('detected_changes', models.JSONField(blank=True, default=dict)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('source_warnings', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('existing_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_candidates', to='game.player')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='game.clubplayerimportjob')),
            ],
            options={
                'verbose_name': 'Spielerimport-Kandidat',
                'verbose_name_plural': 'Spielerimport-Kandidaten',
                'ordering': ['job', 'tm_player_id'],
                'constraints': [models.UniqueConstraint(fields=('job', 'tm_player_id'), name='unique_candidate_per_job_tm_player')],
            },
        ),
    ]
