# Generated by Django 6.0.6 on 2026-06-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0094_club_is_import_placeholder_club_transfermarkt_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='import_name_provisional',
            field=models.BooleanField(default=False, help_text='Beim Anlegen eines neuen Vereins per Spielerimport wurde der Name manuell eingegeben und soll noch durch den von Transfermarkt erkannten Namen bestätigt/aktualisiert werden.', verbose_name='Vereinsname vorläufig (Import)'),
        ),
        migrations.AddField(
            model_name='clubplayerimportjob',
            name='tm_club_name',
            field=models.CharField(blank=True, default='', help_text='Vom lokalen Importer aus der Kaderseite erkannter Vereinsname. Dient zur Bestätigung/Aktualisierung neu angelegter Vereine.', max_length=100),
        ),
    ]
