# Generated by Django 6.0.6 on 2026-06-23 14:30

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0097_tacticsetup_lineup_confirmed_matchday'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso2', models.CharField(help_text='ISO2-Ländercode (Großbuchstaben).', max_length=2, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('continent', models.CharField(blank=True, default='', max_length=40)),
                ('region', models.CharField(blank=True, default='', max_length=40)),
                ('community_points', models.PositiveIntegerField(default=0)),
                ('activity_points', models.PositiveIntegerField(default=0)),
                ('is_paused', models.BooleanField(default=False, help_text='Admin-Sperre: Land wird als gesperrt angezeigt.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Länder-Netzwerk',
                'verbose_name_plural': 'Länder-Netzwerke',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='player',
            name='admin_reviewed',
            field=models.BooleanField(default=False, help_text='Poolspieler wurde von einem Admin freigegeben.', verbose_name='Admin-geprüft'),
        ),
        migrations.AddField(
            model_name='player',
            name='is_callable',
            field=models.BooleanField(default=False, help_text='Spieler darf bei dünnem Pool ergänzend einberufen werden.', verbose_name='Einberufbar'),
        ),
        migrations.AddField(
            model_name='player',
            name='pool_status',
            field=models.CharField(choices=[('none', 'WSC-Spieler (kein Pool)'), ('scoutable', 'Scoutbar (Pool)'), ('auction_reserved', 'Auktion reserviert'), ('unavailable', 'Nicht verfügbar')], default='none', help_text='Steuert die Scouting-Verfügbarkeit. Scoutbar ist nur erlaubt, wenn der Spieler keinen WSC-Verein hat (club=None). Auktion reserviert = Top-Star/Top-Talent, nie über Scouting.', max_length=20, verbose_name='Pool-Status'),
        ),
        migrations.AddField(
            model_name='player',
            name='scouting_category',
            field=models.CharField(blank=True, choices=[('', '– keine –'), ('backup', 'Back-up'), ('ergaenzung', 'Ergänzungsspieler'), ('rotation', 'Rotationsspieler'), ('stammkraft', 'Stammkraft'), ('talent', 'Jugendspieler / Talent'), ('topstar', 'Top-Star'), ('toptalent', 'Top-Talent')], default='', help_text='Absolute Klassifizierung für die Scouting-Suche (Creator-Pflege).', max_length=20, verbose_name='Scouting-Kategorie'),
        ),
        migrations.AddField(
            model_name='player',
            name='wsc_conflict',
            field=models.BooleanField(default=False, help_text='Markiert einen ungeklärten Konflikt mit einer WSC-Vereinszuordnung.', verbose_name='WSC-Konflikt'),
        ),
        migrations.CreateModel(
            name='CommunitySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso2', models.CharField(help_text='ISO2-Ländercode des eingereichten Spielers.', max_length=2)),
                ('tm_url', models.URLField(verbose_name='Transfermarkt-URL')),
                ('player_name', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Offen'), ('approved', 'Angenommen'), ('rejected', 'Abgelehnt')], default='pending', max_length=12)),
                ('week_key', models.CharField(help_text='ISO-Jahr-Woche (z. B. 2026-W26), eingefroren bei Einreichung – für das Wochenlimit.', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_submissions', to='game.managerprofile', verbose_name='Manager')),
            ],
            options={
                'verbose_name': 'Community-Einreichung',
                'verbose_name_plural': 'Community-Einreichungen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScoutingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(choices=[('country', 'Land'), ('region', 'Region')], default='country', max_length=10)),
                ('scope_key', models.CharField(help_text='ISO2-Ländercode (Großbuchstaben) oder Regions-Schlüssel.', max_length=20)),
                ('position', models.CharField(blank=True, default='', help_text='Zielposition (leer = keine Vorgabe).', max_length=10)),
                ('profile', models.CharField(choices=[('backup', 'Back-up'), ('ergaenzung', 'Ergänzungsspieler'), ('rotation', 'Rotationsspieler'), ('stammkraft', 'Stammkraft'), ('talent', 'Jugendspieler / Talent')], default='ergaenzung', max_length=20)),
                ('department_level', models.PositiveSmallIntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('duration_days', models.PositiveSmallIntegerField(default=0)),
                ('started_on', models.DateField(default=django.utils.timezone.localdate)),
                ('completes_on', models.DateField()),
                ('season_id', models.IntegerField(help_text='Eingefrorene Transfermarkt-Saison-ID bei Auftragsstart.')),
                ('status', models.CharField(choices=[('active', 'Aktiv'), ('completed', 'Abgeschlossen'), ('cancelled', 'Abgebrochen')], default='active', max_length=12)),
                ('finds_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scouting_assignments', to='game.club', verbose_name='Verein')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scouting_assignments', to='game.managerprofile', verbose_name='Manager')),
            ],
            options={
                'verbose_name': 'Scoutingauftrag',
                'verbose_name_plural': 'Scoutingaufträge',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScoutingDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Ausbaustufe')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scouting_department', to='game.club', verbose_name='Verein')),
            ],
            options={
                'verbose_name': 'Scoutingabteilung',
                'verbose_name_plural': 'Scoutingabteilungen',
            },
        ),
        migrations.CreateModel(
            name='ScoutingFind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Anzeigereihenfolge 0–2.')),
                ('observer_count', models.PositiveIntegerField(default=0, help_text='Anzahl beobachtender Manager.')),
                ('min_bid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('status', models.CharField(choices=[('offered', 'Vorgeschlagen'), ('chosen', 'Ausgewählt'), ('rejected', 'Abgelehnt'), ('expired', 'Verfallen')], default='offered', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finds', to='game.scoutingassignment')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scouting_finds', to='game.player')),
            ],
            options={
                'verbose_name': 'Scouting-Fund',
                'verbose_name_plural': 'Scouting-Funde',
                'ordering': ['assignment', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ScoutingBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('min_bid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('window_date', models.DateField(help_text='Fester Zuschlagstermin, zu dem dieses Gebot gewertet wird.')),
                ('season_id', models.IntegerField(help_text='Eingefrorene Saison-ID bei Gebotsabgabe.')),
                ('coin_earmarked', models.BooleanField(default=False, help_text='Gebot benötigt einen Hoeneß-Coin-Slot (3.+ Verpflichtung). Coin wird erst bei Gewinn verbraucht.')),
                ('coin_used', models.BooleanField(default=False, help_text='True, wenn ein gewonnenes Gebot tatsächlich einen Coin verbraucht hat.')),
                ('status', models.CharField(choices=[('active', 'Aktiv'), ('won', 'Gewonnen'), ('lost', 'Verloren'), ('cancelled', 'Zurückgezogen')], default='active', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('settled_on', models.DateField(blank=True, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scouting_bids', to='game.club', verbose_name='Verein')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scouting_bids', to='game.managerprofile', verbose_name='Manager')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scouting_bids', to='game.player')),
                ('find', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bids', to='game.scoutingfind')),
            ],
            options={
                'verbose_name': 'Scouting-Gebot',
                'verbose_name_plural': 'Scouting-Gebote',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WatchlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('watched', 'Beobachtet'), ('bid', 'Gebot abgegeben'), ('won', 'Gewonnen'), ('lost', 'Verloren')], default='watched', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_entries', to='game.managerprofile', verbose_name='Manager')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_entries', to='game.player')),
            ],
            options={
                'verbose_name': 'Beobachtungslisten-Eintrag',
                'verbose_name_plural': 'Beobachtungslisten-Einträge',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='scoutingassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('club',), name='unique_active_assignment_per_club'),
        ),
        migrations.AddConstraint(
            model_name='scoutingfind',
            constraint=models.UniqueConstraint(fields=('assignment', 'order'), name='unique_find_order_per_assignment'),
        ),
        migrations.AddConstraint(
            model_name='scoutingbid',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('club', 'player', 'window_date'), name='unique_active_bid_per_club_player_window'),
        ),
        migrations.AddConstraint(
            model_name='watchlistentry',
            constraint=models.UniqueConstraint(fields=('manager', 'player'), name='unique_watchlist_manager_player'),
        ),
    ]
