# Generated by Django 6.0.6 on 2026-06-25 13:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0098_countrynetwork_player_admin_reviewed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='code',
            field=models.CharField(choices=[('TM', 'Transfermarkt'), ('FM', 'FMInside'), ('CMTRACKER', 'CMTracker'), ('API_FOOTBALL', 'API-Football'), ('WSC', 'Websoccer')], max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='playerimportcandidate',
            name='status',
            field=models.CharField(choices=[('new', 'Neuer Spieler'), ('existing_changed', 'Vorhanden — geändert'), ('existing_unchanged', 'Vorhanden — unverändert'), ('missing_fmi', 'FMInside fehlt'), ('missing_sofifa', 'CMTracker fehlt'), ('ambiguous_fmi', 'FMInside mehrdeutig'), ('ambiguous_sofifa', 'CMTracker mehrdeutig'), ('invalid', 'Ungültig'), ('source_error', 'Quellenfehler'), ('ready', 'Importbereit'), ('imported', 'Importiert'), ('skipped', 'Übersprungen')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='playersourcerating',
            name='defensivstellung',
            field=models.PositiveSmallIntegerField(blank=True, help_text='FMI: Positioning (defensiv) / CMTracker: Stellungsspiel.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='playersourcerating',
            name='source',
            field=models.CharField(choices=[('CMTRACKER', 'CMTracker'), ('FM', 'FMInside')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sourceimportrun',
            name='source',
            field=models.CharField(choices=[('cmtracker', 'CMTracker')], default='cmtracker', max_length=20),
        ),
    ]
