# Generated by Django 6.0.6 on 2026-06-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0102_extern_loan_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='loan_status',
            field=models.CharField(blank=True, choices=[('none', 'Kein Leihverhältnis'), ('loaned_in', 'Geliehen'), ('loaned_out', 'Verliehen'), ('extern_loan', 'Extern verliehen')], default='none', help_text='Geliehen = im Verein aktiv, gehört einem anderen Verein. Verliehen = gehört diesem Verein, spielt aktuell woanders.', max_length=12, verbose_name='Leihstatus'),
        ),
    ]
