# Generated by Django 6.0.6 on 2026-06-28 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0103_alter_player_loan_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scoutingdepartment',
            options={'verbose_name': 'Scoutingbüro', 'verbose_name_plural': 'Scoutingbüros'},
        ),
        migrations.AlterField(
            model_name='scoutingassignment',
            name='position',
            field=models.CharField(blank=True, default='', help_text='Zielposition(en), kommagetrennt bei Mehrfachauswahl (leer = keine Vorgabe).', max_length=80),
        ),
    ]
