# Generated by Django 6.0.6 on 2026-07-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0104_scouting_position_multiselect'),
    ]

    operations = [
        migrations.CreateModel(
            name='StadionumfeldConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stadionumfeld-Konfiguration',
                'verbose_name_plural': 'Stadionumfeld-Konfiguration',
            },
        ),
    ]
