# Generated by Django 6.0.6 on 2026-07-05 20:56

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0105_stadionumfeldconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityConstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.CharField(help_text='Serverseitiger Einrichtungs-Key (z. B. nlz, medizin, training, office).', max_length=32, verbose_name='Einrichtung')),
                ('target_level', models.PositiveSmallIntegerField(verbose_name='Zielstufe')),
                ('cost_paid', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Bezahlte Baukosten')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Baubeginn')),
                ('completes_at', models.DateTimeField(verbose_name='Fertigstellung')),
                ('status', models.CharField(choices=[('active', 'Im Bau'), ('done', 'Abgeschlossen'), ('cancelled', 'Abgebrochen')], default='active', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_constructions', to='game.club', verbose_name='Verein')),
            ],
            options={
                'verbose_name': 'Einrichtungs-Ausbau',
                'verbose_name_plural': 'Einrichtungs-Ausbauten',
                'ordering': ['-started_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('club', 'facility'), name='uniq_active_facility_construction_per_club')],
            },
        ),
    ]
