# Generated by Django 6.0.7 on 2026-07-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0106_facilityconstruction'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubnewsitem',
            name='blocks',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='clubnewsitem',
            name='card_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clubnewsitem',
            name='category',
            field=models.CharField(default='Sonstiges', max_length=50),
        ),
        migrations.AddField(
            model_name='clubnewsitem',
            name='img_height',
            field=models.PositiveSmallIntegerField(default=120),
        ),
        migrations.AddField(
            model_name='clubnewsitem',
            name='img_path',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AddField(
            model_name='clubnewsitem',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clubnewsitem',
            name='is_social',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clubnewsitem',
            name='outlet',
            field=models.CharField(default='Vereinsredaktion', max_length=50),
        ),
        migrations.AddField(
            model_name='clubnewsitem',
            name='subtitle',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='clubnewsitem',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
