# Generated by Django 6.0.7 on 2026-07-14 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0107_vereinsnews_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulatedmatch',
            name='match_no',
            field=models.PositiveIntegerField(blank=True, help_text='Laufende Spielnummer innerhalb der Saison, beginnt je Saison bei 1.', null=True, verbose_name='Spiel-Nr. (Saison)'),
        ),
        migrations.AddField(
            model_name='simulatedmatch',
            name='season',
            field=models.CharField(db_index=True, default='0', help_text='Saison, in der das Spiel stattfand (z. B. "0", "1").', max_length=10, verbose_name='Saison'),
        ),
        migrations.AddConstraint(
            model_name='simulatedmatch',
            constraint=models.UniqueConstraint(condition=models.Q(('match_no__isnull', False)), fields=('season', 'match_no'), name='uniq_simulatedmatch_season_match_no'),
        ),
    ]
