# Generated by Django 6.0.7 on 2026-07-14 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0109_backfill_simulatedmatch_season_match_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerTimelineEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(blank=True, max_length=150)),
                ('event_date', models.DateField()),
                ('category', models.CharField(choices=[('verein', 'Verein'), ('titel', 'Titel'), ('finale', 'Finale'), ('jugend', 'Jugend'), ('status', 'Status')], max_length=12)),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField(blank=True)),
                ('result_text', models.CharField(blank=True, max_length=20)),
                ('show_trophy', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_timeline_entries', to='game.club')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_entries', to='game.managerprofile')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_timeline_entries', to='game.player')),
            ],
            options={
                'verbose_name': 'Manager-Timeline-Eintrag',
                'verbose_name_plural': 'Manager-Timeline-Einträge',
                'ordering': ['event_date', 'id'],
            },
        ),
    ]
