# Generated by Django 6.0.7 on 2026-07-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0110_managertimelineentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='managertimelineentry',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managertimelineentry',
            name='status',
            field=models.CharField(choices=[('pending', 'Ausstehend'), ('approved', 'Genehmigt'), ('rejected', 'Abgelehnt')], default='pending', max_length=12),
        ),
    ]
