# Generated by Django 6.0.7 on 2026-07-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0111_timeline_entry_moderation'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='cmtracker_id',
            field=models.BigIntegerField(blank=True, help_text='CMTracker-Vereins-ID (Spalte existiert live bereits manuell).', null=True),
        ),
    ]
