# Generated by Django 6.0.7 on 2026-07-17 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0114_managerprofile_last_seen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clubnewsitem',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_news', to=settings.AUTH_USER_MODEL, verbose_name='Verfasser'),
        ),
        migrations.AlterField(
            model_name='league',
            name='logo_static_path',
            field=models.CharField(blank=True, help_text='Pfad zum Liga-Logo im Format competitions/{id}_comp.png — wird automatisch beim Hochladen gesetzt, nicht manuell befüllen.', max_length=240),
        ),
        migrations.AlterField(
            model_name='mediaoutlet',
            name='accent_color',
            field=models.CharField(default='#22e6ff', help_text='Hex-Akzentfarbe für Fallback-Badge', max_length=7),
        ),
        migrations.AlterField(
            model_name='mediaoutlet',
            name='has_logo',
            field=models.BooleanField(default=False, help_text='True wenn PNG unter ASSETS_ROOT/media/ vorhanden'),
        ),
        migrations.AlterField(
            model_name='mediaoutlet',
            name='slug',
            field=models.SlugField(help_text='Dateiname ohne _media.png, z.B. kicker', max_length=60, unique=True),
        ),
    ]
