# Generated by Django 6.0.7 on 2026-07-19 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0115_clubnewsitem_published_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerClubHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.PositiveSmallIntegerField(help_text='Globale Saisonnummer (GameSeasonState, beginnt bei 0).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_club_history', to='game.club')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_history', to='game.player')),
            ],
            options={
                'verbose_name': 'Vereinsstation',
                'verbose_name_plural': 'Vereinsstationen',
                'ordering': ['season', 'id'],
                'constraints': [models.UniqueConstraint(fields=('player', 'club', 'season'), name='unique_player_club_history_season')],
            },
        ),
    ]
