# Generated by Django 6.0.7 on 2026-07-19 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0117_normalize_tx_seasons'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='game.managerprofile')),
            ],
            options={
                'verbose_name': 'Manager-Notizen',
                'verbose_name_plural': 'Manager-Notizen',
            },
        ),
    ]
