# Generated by Django 6.0.7 on 2026-07-19 17:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0118_managernotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonEconomySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saison', models.CharField(max_length=20, unique=True, verbose_name='Saison')),
                ('mw_median', models.DecimalField(decimal_places=2, max_digits=15)),
                ('staerke_median', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('potential_median', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('mw_kurve_json', models.JSONField(blank=True, default=dict)),
                ('gehalts_anker', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Saison-Ökonomie-Snapshot',
                'verbose_name_plural': 'Saison-Ökonomie-Snapshots',
                'ordering': ['-saison'],
            },
        ),
        migrations.CreateModel(
            name='EconomyParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saison', models.CharField(max_length=20, verbose_name='Saison')),
                ('key', models.CharField(max_length=64, verbose_name='Parameter-Key')),
                ('value', models.JSONField(verbose_name='Wert')),
            ],
            options={
                'verbose_name': 'Economy-Parameter',
                'verbose_name_plural': 'Economy-Parameter',
                'ordering': ['key', 'saison'],
                'unique_together': {('saison', 'key')},
            },
        ),
        migrations.CreateModel(
            name='FinanceMatchdayRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saison', models.CharField(max_length=20)),
                ('spieltag', models.PositiveSmallIntegerField()),
                ('run_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_matchday_runs', to='game.club')),
            ],
            options={
                'verbose_name': 'Finanz-Spieltagslauf',
                'verbose_name_plural': 'Finanz-Spieltagsläufe',
                'ordering': ['-run_at'],
                'unique_together': {('club', 'saison', 'spieltag')},
            },
        ),
        migrations.CreateModel(
            name='FinanceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saison', models.CharField(blank=True, max_length=20, verbose_name='Saison')),
                ('spieltag', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Spieltag')),
                ('typ', models.CharField(choices=[('TICKET', 'Ticketverkauf'), ('UMFELD', 'Stadionumfeld-Umsatz'), ('SPONSOR_FIX', 'Sponsor (Fixrate)'), ('SPONSOR_VARIABEL', 'Sponsor (variabel)'), ('TV_SOCKEL', 'TV-Gelder (Sockel)'), ('TV_PLATZ', 'TV-Gelder (Platzierung)'), ('TV_KOEFF', 'TV-Gelder (Koeffizient)'), ('FALLSCHIRM', 'Fallschirmzahlung'), ('PRAEMIE_POKAL', 'Pokalprämie'), ('PRAEMIE_SUPERCUP', 'Supercup-Prämie'), ('PRAEMIE_INTL', 'Internationale Prämie'), ('ABFINDUNG', 'Abfindung (Todesfall)'), ('TRANSFER_EIN', 'Transfer (Einnahme)'), ('TRANSFER_AUS', 'Transfer (Ausgabe)'), ('AUSBILDUNG_EIN', 'Ausbildungsabgabe (Einnahme)'), ('AUSBILDUNG_AUS', 'Ausbildungsabgabe (Ausgabe)'), ('GEHALT', 'Gehälter'), ('BETRIEB', 'Betriebskosten'), ('STADION_UNTERHALT', 'Stadionunterhalt'), ('STADION_SPIELTAG', 'Spieltagskosten'), ('AUSBAU', 'Stadionausbau'), ('UMFELD_AUSBAU', 'Stadionumfeld-Ausbau'), ('SCOUTING', 'Scouting'), ('AUKTION', 'Auktion'), ('STRAFE', 'Sportgericht-Strafe'), ('VERBANDSABGABE', 'Verbandsabgabe'), ('KORREKTUR_ADMIN', 'Admin-Korrektur')], max_length=32, verbose_name='Buchungstyp')),
                ('betrag', models.DecimalField(decimal_places=2, help_text='Positiv = Einnahme, Negativ = Ausgabe.', max_digits=14, verbose_name='Betrag (€)')),
                ('referenz_typ', models.CharField(blank=True, default='', max_length=32)),
                ('referenz_id', models.PositiveIntegerField(blank=True, null=True)),
                ('beschreibung', models.CharField(blank=True, default='', max_length=200, verbose_name='Verwendungszweck')),
                ('datum', models.DateField(default=django.utils.timezone.localdate, verbose_name='Buchungsdatum')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_transactions', to='game.club', verbose_name='Verein')),
            ],
            options={
                'verbose_name': 'Finanzbuchung',
                'verbose_name_plural': 'Finanzbuchungen',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['club', 'saison'], name='game_financ_club_id_dafc9b_idx'), models.Index(fields=['saison', 'typ'], name='game_financ_saison_8ebc94_idx'), models.Index(fields=['club', 'created_at'], name='game_financ_club_id_5c18bb_idx')],
            },
        ),
    ]
