# Generated by Django 6.0.7 on 2026-07-19 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0121_migrate_legacy_finance'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonFinanceState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saison', models.CharField(max_length=20, unique=True, verbose_name='Saison')),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('report_json', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Saison-Finanzstatus',
                'verbose_name_plural': 'Saison-Finanzstatus',
                'ordering': ['-saison'],
            },
        ),
        migrations.AddField(
            model_name='league',
            name='level',
            field=models.PositiveSmallIntegerField(default=1, help_text='Ebene im Ligasystem des Landes: 1 = Erstliga, 2 = Zweitliga. Steuert TV_SPLIT_LIGA und SPONSOR_SOCKEL (Finanzsystem Kap. 6/7).', verbose_name='Liga-Ebene'),
        ),
        migrations.CreateModel(
            name='LandKoeffizient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land', models.CharField(max_length=80, verbose_name='Land')),
                ('saison', models.CharField(max_length=20, verbose_name='Saison')),
                ('punkte', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Punkte')),
            ],
            options={
                'verbose_name': 'Landeskoeffizient',
                'verbose_name_plural': 'Landeskoeffizienten',
                'ordering': ['saison', '-punkte'],
                'unique_together': {('land', 'saison')},
            },
        ),
        migrations.CreateModel(
            name='TVPot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saison', models.CharField(max_length=20, verbose_name='Saison')),
                ('land', models.CharField(max_length=80, verbose_name='Land')),
                ('rang', models.PositiveSmallIntegerField(verbose_name='Koeffizienten-Rang')),
                ('gesamt', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Gesamttopf (€)')),
            ],
            options={
                'verbose_name': 'TV-Ländertopf',
                'verbose_name_plural': 'TV-Ländertöpfe',
                'ordering': ['saison', 'rang'],
                'unique_together': {('saison', 'land')},
            },
        ),
        migrations.CreateModel(
            name='SponsorOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saison', models.CharField(max_length=20, verbose_name='Saison')),
                ('typ', models.CharField(choices=[('sicherheit', 'Sicherheit (100 % fix)'), ('sieggeld', 'Sieggeld (fix + €/Sieg)'), ('zieljaeger', 'Zieljäger (fix + Zielbonus)'), ('zuschauer', 'Zuschauer (fix + €/Besucher)')], max_length=20, verbose_name='Angebotstyp')),
                ('sponsor_name', models.CharField(max_length=100, verbose_name='Sponsorname')),
                ('fix_betrag', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Fixbetrag / Saison (€)')),
                ('variable_json', models.JSONField(blank=True, default=dict, verbose_name='Variabler Anteil')),
                ('erwartungswert', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Erwartungswert (€)')),
                ('gewaehlt', models.BooleanField(default=False, verbose_name='Gewählt')),
                ('angenommen_at', models.DateTimeField(blank=True, null=True, verbose_name='Angenommen am')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_offers', to='game.club', verbose_name='Verein')),
            ],
            options={
                'verbose_name': 'Sponsorangebot',
                'verbose_name_plural': 'Sponsorangebote',
                'ordering': ['club', 'saison', 'id'],
                'indexes': [models.Index(fields=['club', 'saison'], name='game_sponso_club_id_61faac_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('gewaehlt', True)), fields=('club', 'saison'), name='unique_chosen_sponsor_offer_per_season')],
            },
        ),
        migrations.CreateModel(
            name='VereinKoeffizient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saison', models.CharField(max_length=20, verbose_name='Saison')),
                ('punkte', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Punkte')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='koeffizienten', to='game.club', verbose_name='Verein')),
            ],
            options={
                'verbose_name': 'Vereinskoeffizient',
                'verbose_name_plural': 'Vereinskoeffizienten',
                'ordering': ['saison', '-punkte'],
                'unique_together': {('club', 'saison')},
            },
        ),
    ]
