# Generated by Django 6.0.7 on 2026-07-19 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0125_seed_stadium_phase3_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchdayrevenue',
            name='attendance_seating',
            field=models.PositiveIntegerField(default=0, verbose_name='Zuschauer Sitzplätze'),
        ),
        migrations.AddField(
            model_name='matchdayrevenue',
            name='attendance_standing',
            field=models.PositiveIntegerField(default=0, verbose_name='Zuschauer Stehplätze'),
        ),
        migrations.AddField(
            model_name='matchdayrevenue',
            name='attendance_vip',
            field=models.PositiveIntegerField(default=0, verbose_name='Zuschauer VIP'),
        ),
        migrations.AddField(
            model_name='stadiumexpansion',
            name='applied',
            field=models.BooleanField(default=True, help_text='True, sobald die Plätze auf das Stadion gebucht wurden.', verbose_name='Kapazität übernommen'),
        ),
        migrations.AddField(
            model_name='stadiumexpansion',
            name='completes_at',
            field=models.DateTimeField(blank=True, help_text='Wanduhr-Zeitpunkt, ab dem die Plätze aktiv werden (leer = sofort).', null=True, verbose_name='Fertigstellung'),
        ),
        migrations.CreateModel(
            name='ClubStadionumfeldState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stadionumfeld_state', to='game.club', verbose_name='Verein')),
            ],
            options={
                'verbose_name': 'Stadionumfeld-Zustand (Verein)',
                'verbose_name_plural': 'Stadionumfeld-Zustände (Vereine)',
            },
        ),
    ]
