# Generated by Django 6.0.7 on 2026-07-19 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0127_migrate_stadionumfeld_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='sale_category',
            field=models.CharField(choices=[('GELD', 'Verkauf gegen Geld'), ('TAUSCH', 'Nur Tausch'), ('GELD_TAUSCH', 'Geld oder Tausch'), ('UVK', 'Unverkäuflich')], default='UVK', help_text='Manager-Markierung: KI bietet nur auf GELD und GELD_TAUSCH — und nur, wenn die Markierung sichtbar ist.', max_length=12, verbose_name='Verkaufskategorie'),
        ),
        migrations.AddField(
            model_name='player',
            name='sale_visible_to_ai',
            field=models.BooleanField(default=False, help_text='Nur sichtbar geschaltete Markierungen erhalten KI-Angebote (Postfach-Hygiene).', verbose_name='Markierung für KI sichtbar'),
        ),
        migrations.CreateModel(
            name='TransferNegotiation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('gegenforderung', 'Gegenforderung — Manager am Zug'), ('deal', 'Abgeschlossen'), ('abgelehnt', 'Abgelehnt')], max_length=16, verbose_name='Status')),
                ('runde', models.PositiveSmallIntegerField(default=1, verbose_name='Runde')),
                ('letztes_gebot', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Letztes Gebot (€)')),
                ('gegenforderung', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Gegenforderung (€)')),
                ('noise_seed', models.CharField(editable=False, max_length=64)),
                ('cooldown_until', models.DateTimeField(blank=True, null=True, verbose_name='Cooldown bis')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bidder_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_bids', to='game.club', verbose_name='Bietender Verein')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_negotiations', to='game.player', verbose_name='Spieler')),
                ('seller_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_sales', to='game.club', verbose_name='Verkaufender Verein')),
            ],
            options={
                'verbose_name': 'Transferverhandlung',
                'verbose_name_plural': 'Transferverhandlungen',
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'gegenforderung')), fields=('player', 'bidder_club'), name='unique_active_transfer_negotiation')],
            },
        ),
    ]
