# Generated by Django 6.0.7 on 2026-07-19 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0129_seed_finance_phase4'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForcedAuction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_bid', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Mindestgebot (€)')),
                ('ends_on', models.DateField(verbose_name='Zuschlagstermin')),
                ('status', models.CharField(choices=[('open', 'Laufend'), ('settled', 'Zugeschlagen'), ('unsold', 'Kein Zuschlag'), ('cancelled', 'Abgebrochen')], default='open', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('settled_on', models.DateField(blank=True, null=True, verbose_name='Gewertet am')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forced_auctions', to='game.player')),
                ('seller_club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forced_auctions', to='game.club', verbose_name='Schuldner-Verein')),
            ],
            options={
                'verbose_name': 'Zwangsversteigerung',
                'verbose_name_plural': 'Zwangsversteigerungen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForcedAuctionBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Gebot (€)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='game.forcedauction')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forced_auction_bids', to='game.club', verbose_name='Bieter')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forced_auction_bids', to='game.managerprofile')),
            ],
            options={
                'verbose_name': 'Zwangsversteigerungs-Gebot',
                'verbose_name_plural': 'Zwangsversteigerungs-Gebote',
                'ordering': ['-amount', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='forcedauction',
            name='winning_bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='game.forcedauctionbid', verbose_name='Zuschlags-Gebot'),
        ),
        migrations.CreateModel(
            name='InsolvencyCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(auto_now_add=True, verbose_name='Eröffnet am')),
                ('deadline_at', models.DateTimeField(verbose_name='Frist (7 echte Tage)')),
                ('betrag_bei_eroeffnung', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Kontostand bei Eröffnung (€)')),
                ('status', models.CharField(choices=[('open', 'Offen'), ('resolved', 'Bereinigt'), ('enforced', 'Zwangsversteigerung eingeleitet')], default='open', max_length=12)),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Bereinigt am')),
                ('enforced_at', models.DateTimeField(blank=True, null=True, verbose_name='Vollstreckt am')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insolvency_cases', to='game.club', verbose_name='Verein')),
                ('trigger_tx', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='game.financetransaction', verbose_name='Auslösende Buchung')),
            ],
            options={
                'verbose_name': 'Zahlungsunfähigkeits-Vermerk',
                'verbose_name_plural': 'Zahlungsunfähigkeits-Vermerke',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.AddField(
            model_name='forcedauction',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forced_auctions', to='game.insolvencycase', verbose_name='Vermerk'),
        ),
        migrations.AddConstraint(
            model_name='forcedauctionbid',
            constraint=models.UniqueConstraint(fields=('auction', 'club'), name='unique_forced_auction_bid_per_club'),
        ),
        migrations.AddConstraint(
            model_name='insolvencycase',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('club',), name='unique_open_insolvency_case_per_club'),
        ),
        migrations.AddConstraint(
            model_name='forcedauction',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('player',), name='unique_open_forced_auction_per_player'),
        ),
    ]
