# Generated by Django 6.0.7 on 2026-07-19 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0131_seed_verbandsabgabe'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='ai_buyer_paused',
            field=models.BooleanField(default=False, help_text='Pausiert den KI-Käufer-Prüflauf dieses Vereins (Admin-Eingriff über die KI-Transferzentrale).', verbose_name='KI-Käufer pausiert'),
        ),
        migrations.AddField(
            model_name='gameseasonstate',
            name='transfer_window_id',
            field=models.CharField(blank=True, default='', help_text='Kennung des aktuellen/letzten Fensters (z. B. "0-S1"). Fenster-Zähler und Talent-Cooldowns hängen an dieser ID.', max_length=20, verbose_name='Transferfenster-ID'),
        ),
        migrations.AddField(
            model_name='gameseasonstate',
            name='transfer_window_open',
            field=models.BooleanField(default=False, help_text='Admin-Schalter (KI-Transferzentrale): Nur bei offenem Fenster laufen KI-Käufer-Prüfläufe.', verbose_name='Transferfenster offen'),
        ),
        migrations.CreateModel(
            name='AIBuyerRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saison', models.CharField(max_length=20)),
                ('spieltag', models.PositiveSmallIntegerField()),
                ('trigger', models.CharField(choices=[('spieltag', 'Spieltag'), ('verkauf', 'Eigener Verkauf'), ('monatsupdate', 'Monats-Datenupdate'), ('finanzlage', 'Finanzlagenwechsel'), ('manuell', 'Manuell')], default='spieltag', max_length=16)),
                ('dry_run', models.BooleanField(default=False)),
                ('window_id', models.CharField(blank=True, default='', max_length=20)),
                ('report', models.JSONField(blank=True, default=dict)),
                ('run_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_buyer_runs', to='game.club')),
            ],
            options={
                'verbose_name': 'KI-Käufer-Prüflauf',
                'verbose_name_plural': 'KI-Käufer-Prüfläufe',
                'ordering': ['-run_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('trigger', 'spieltag')), fields=('club', 'saison', 'spieltag'), name='unique_ai_buyer_matchday_run')],
            },
        ),
        migrations.CreateModel(
            name='AITransferOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kauftyp', models.CharField(choices=[('bedarf', 'Bedarfskauf'), ('qualitaet', 'Qualitätskauf'), ('talent', 'Talentkauf')], max_length=12, verbose_name='Kauftyp')),
                ('bewertung', models.DecimalField(decimal_places=2, editable=False, max_digits=15, verbose_name='Interne Bewertung (€)')),
                ('max_gebot', models.DecimalField(decimal_places=2, editable=False, max_digits=15, verbose_name='Käufer-Maximum (€)')),
                ('aktuelles_gebot', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Aktuelles Gebot (€)')),
                ('stufe', models.PositiveSmallIntegerField(default=1, verbose_name='Gebotsstufe (1–3)')),
                ('status', models.CharField(choices=[('berechnet', 'Berechnet (Trockenlauf)'), ('versendet', 'Versendet — Manager am Zug'), ('abgelehnt', 'Abgelehnt'), ('deal', 'Deal'), ('storniert', 'Storniert'), ('abgelaufen', 'Abgelaufen')], default='berechnet', max_length=12, verbose_name='Status')),
                ('dry_run', models.BooleanField(default=False, verbose_name='Trockenlauf')),
                ('window_id', models.CharField(blank=True, default='', max_length=20, verbose_name='Fenster-ID')),
                ('noise_seed', models.CharField(editable=False, max_length=64)),
                ('gueltig_bis', models.DateTimeField(blank=True, null=True, verbose_name='Gültig bis')),
                ('cooldown_until', models.DateTimeField(blank=True, null=True, verbose_name='Cooldown bis')),
                ('luecken_score', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Lückenscore')),
                ('begruendung', models.TextField(blank=True, default='', verbose_name='Begründung (Admin-Review)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_buy_offers', to='game.club', verbose_name='Bietender KI-Verein')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_transfer_offers', to='game.player', verbose_name='Zielspieler')),
                ('seller_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_incoming_offers', to='game.club', verbose_name='Besitzerverein')),
            ],
            options={
                'verbose_name': 'KI-Kaufangebot',
                'verbose_name_plural': 'KI-Kaufangebote',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['status', 'window_id'], name='game_aitran_status_d21c07_idx'), models.Index(fields=['seller_club', 'status'], name='game_aitran_seller__0771ef_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ('berechnet', 'versendet'))), fields=('buyer_club', 'player'), name='unique_open_ai_transfer_offer')],
            },
        ),
    ]
