# Generated by Django 6.0.7 on 2026-07-24 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0140_aitransferoffer_ki_meta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fm_uid', models.BigIntegerField(blank=True, help_text='Football-Manager interne UID (für Profilbild /assets/referees/face_{fm_uid}.png).', null=True, unique=True, verbose_name='FM UID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('nationality', models.CharField(blank=True, help_text='z. B. "Schweiz", "Frankreich"', max_length=80, verbose_name='Nationalität (DE)')),
                ('nationality_code', models.CharField(blank=True, help_text='Assetserver-Code für flag_url(), z. B. "771" (CH) oder ISO-2 "fr".', max_length=10, verbose_name='Flaggen-Code')),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Alter')),
                ('level', models.CharField(choices=[('weltklasse', 'Weltklasse'), ('international', 'International'), ('erste-liga', 'Erste Liga'), ('zweite-liga', 'Zweite Liga'), ('aufsteiger', 'Aufsteiger')], default='international', max_length=20, verbose_name='Niveau')),
                ('quote', models.CharField(blank=True, help_text='Erscheint kursiv im Popup, z. B. „Souveräner Spielleiter".', max_length=200, verbose_name='Kurzcharakter')),
                ('karten_tendenz', models.CharField(choices=[('nachsichtig', 'Nachsichtig'), ('ausgewogen', 'Ausgewogen'), ('kartenfreudig', 'Kartenfreudig')], default='ausgewogen', max_length=20, verbose_name='Karten-Tendenz')),
                ('spielfluss_tendenz', models.CharField(choices=[('pfeift_viel_ab', 'Pfeift viel ab'), ('ausgewogen', 'Ausgewogen'), ('laesst_laufen', 'Lässt laufen')], default='ausgewogen', max_length=20, verbose_name='Spielfluss-Tendenz')),
                ('vorsaison_spiele', models.PositiveSmallIntegerField(default=0, verbose_name='Spiele (Vorsaison)')),
                ('vorsaison_gelb_avg', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Ø Gelb/Spiel (Vorsaison)')),
                ('vorsaison_rot', models.PositiveSmallIntegerField(default=0, verbose_name='Rote Karten (Vorsaison)')),
                ('vorsaison_elfmeter', models.PositiveSmallIntegerField(default=0, verbose_name='Elfmeter (Vorsaison)')),
                ('vorsaison_umstritten', models.PositiveSmallIntegerField(default=0, verbose_name='Umstrittene Ents. (Vorsaison)')),
                ('vorsaison_competitions', models.JSONField(blank=True, default=list, help_text='Liste von Wettbewerbsnamen, z. B. ["1. Bundesliga", "DFB-Pokal"].', verbose_name='Wettbewerbe (Vorsaison)')),
            ],
            options={
                'verbose_name': 'Schiedsrichter',
                'verbose_name_plural': 'Schiedsrichter',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='financematchdayrun',
            name='typ',
            field=models.CharField(blank=True, default='', help_text='Buchungstyp-Guard (leer = Haupt-Zeitstempel-Anker; TV_SOCKEL / SPONSOR / TICKET / GEHALT / STADION / BETRIEB = Schritt-Marker).', max_length=30),
        ),
        migrations.AddField(
            model_name='simulatedmatch',
            name='referee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='game.referee', verbose_name='Schiedsrichter'),
        ),
    ]
