# Generated by Django 6.0.7 on 2026-07-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0144_seed_sponsor_v2_params'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sponsor',
            new_name='game_sponso_bereich_7e9aac_idx',
            old_name='game_sponsor_bereich_aktiv_idx',
        ),
        migrations.RenameIndex(
            model_name='sponsorcontract',
            new_name='game_sponso_saison_75351b_idx',
            old_name='game_sponsorcontract_saison_club_idx',
        ),
        migrations.RenameIndex(
            model_name='sponsorcontract',
            new_name='game_sponso_club_id_3a1d0c_idx',
            old_name='game_sponsorcontract_club_saison_abg_idx',
        ),
        migrations.RenameIndex(
            model_name='sponsoroffer',
            new_name='game_sponso_club_id_1f1216_idx',
            old_name='game_sponoffer_club_saison_slot_idx',
        ),
        migrations.AlterField(
            model_name='referee',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Format DD.MM.YYYY; Alter wird zur Laufzeit berechnet.', null=True, verbose_name='Geburtsdatum'),
        ),
        migrations.AlterField(
            model_name='referee',
            name='nationality_code',
            field=models.CharField(blank=True, help_text='Assetserver-Code für flag_url(), z. B. "771" oder ISO-2 "de".', max_length=10, verbose_name='Flaggen-Code'),
        ),
        migrations.AlterField(
            model_name='referee',
            name='quote',
            field=models.PositiveSmallIntegerField(default=10, help_text='1=fehlerhaft, 20=makellos. P(Fehlentscheidung/Sp) = clamp((14−quote)×0.7; 1; 8)%.', verbose_name='Entscheidungsqualität (1–20)'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sponsorcontract',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
