# Generated by Django 6.0.7 on 2026-07-24 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0146_sponsoroffer_status_typ_torgeld'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='domain',
            field=models.CharField(blank=True, max_length=120, verbose_name='Domain (z.B. fritz-kola.de)'),
        ),
    ]
