# Generated by Django 6.0.7 on 2026-07-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0151_fix_sponsor_risk_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayWeather',
            fields=[
                ('sim_day', models.DateField(help_text='Kalenderdatum des Sim-Tags (globaler Kalender).', primary_key=True, serialize=False, verbose_name='Sim-Tag')),
                ('weather_type', models.CharField(choices=[('normal', 'Normal'), ('regen', 'Regen'), ('wind', 'Starker Wind'), ('nebel', 'Nebel'), ('hitze', 'Hitze'), ('schnee', 'Schnee/Frost')], max_length=10, verbose_name='Wetterart')),
                ('temperature', models.SmallIntegerField(help_text='Reiner Anzeigewert ohne Mechanik.', verbose_name='Temperatur (°C)')),
            ],
            options={
                'verbose_name': 'Tageswetter',
                'verbose_name_plural': 'Tageswetter',
                'ordering': ['sim_day'],
            },
        ),
    ]
