# Generated by Django 6.0.7 on 2026-08-04 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0152_day_weather'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zweck', models.CharField(help_text="Modul-Kennung, z. B. 'showauction'.", max_length=32)),
                ('referenz', models.CharField(help_text="Eindeutige Referenz, z. B. 'showauction:bid:42'.", max_length=64)),
                ('betrag', models.DecimalField(decimal_places=2, default=0, help_text='Reservierter Geldbetrag (≥ 0).', max_digits=14)),
                ('slots', models.PositiveSmallIntegerField(default=0, help_text='Reservierte Kaderplätze.')),
                ('status', models.CharField(choices=[('active', 'Aktiv'), ('released', 'Freigegeben'), ('consumed', 'Verbraucht (gebucht)')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Finanz-Reservierung',
                'verbose_name_plural': 'Finanz-Reservierungen',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('body', models.CharField(blank=True, default='', max_length=240)),
                ('url', models.CharField(blank=True, default='', max_length=200)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Benachrichtigung',
                'verbose_name_plural': 'Benachrichtigungen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='player',
            name='transfer_locked_until',
            field=models.DateField(blank=True, help_text='Bis zu diesem Datum (exklusiv) ist kein Vereinswechsel möglich. Wird u. a. beim Show-Auktions-Zuschlag gesetzt (21 Tage).', null=True, verbose_name='Wechselsperre bis'),
        ),
        migrations.AlterField(
            model_name='cointransaction',
            name='reason',
            field=models.CharField(choices=[('win', 'Sieg'), ('big_win', 'Kantersieg'), ('season_goal', 'Saisonziel erfüllt'), ('boost_transfer', 'Transfermarkt-Boost'), ('scout_talent', 'Talentscout'), ('show_auction', 'Show-Auktion (Eintritt)')], max_length=30),
        ),
        migrations.AlterField(
            model_name='player',
            name='pool_status',
            field=models.CharField(choices=[('none', 'WSC-Spieler (kein Pool)'), ('scoutable', 'Scoutbar (Pool)'), ('auction_reserved', 'Auktion reserviert'), ('unavailable', 'Nicht verfügbar'), ('show_auction', 'Show-Auktion (Raum)')], default='none', help_text='Steuert die Scouting-Verfügbarkeit. Scoutbar ist nur erlaubt, wenn der Spieler keinen WSC-Verein hat (club=None). Auktion reserviert = Top-Star/Top-Talent, nie über Scouting.', max_length=20, verbose_name='Pool-Status'),
        ),
        migrations.AddConstraint(
            model_name='financetransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('referenz_typ', 'showauction_settle')), fields=('referenz_typ', 'referenz_id'), name='unique_showauction_settle_booking'),
        ),
        migrations.AddField(
            model_name='financereservation',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_reservations', to='game.club', verbose_name='Verein'),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='game.managerprofile'),
        ),
        migrations.AddIndex(
            model_name='financereservation',
            index=models.Index(fields=['club', 'status'], name='game_financ_club_id_ee282d_idx'),
        ),
        migrations.AddConstraint(
            model_name='financereservation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('referenz',), name='unique_active_finance_reservation'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='game_notifi_recipie_b62a34_idx'),
        ),
    ]
