# Generated by Django 6.0.7 on 2026-08-12 16:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0153_financereservation_notification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionBarometer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=10, unique=True)),
                ('supply', models.PositiveIntegerField(default=0, verbose_name='Angebot')),
                ('demand', models.PositiveIntegerField(default=0, verbose_name='Nachfrage')),
                ('weight', models.DecimalField(decimal_places=3, default=Decimal('1.000'), help_text='> 1 = Nachfrageüberhang (teurer), < 1 = Angebotsüberhang.', max_digits=5, verbose_name='Preisgewicht')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Positionsbarometer',
                'verbose_name_plural': 'Positionsbarometer',
            },
        ),
        migrations.AddField(
            model_name='club',
            name='reserved',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cache der aktiven harten Reservierungen (Transfersystem v2).', max_digits=15, verbose_name='Reserviert (€)'),
        ),
        migrations.CreateModel(
            name='BuybackClause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('deadline', models.DateField()),
                ('preemption_until', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('holder_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyback_clauses', to='game.club')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyback_clauses', to='game.player')),
            ],
            options={
                'verbose_name': 'Rückkaufoption',
                'verbose_name_plural': 'Rückkaufoptionen',
            },
        ),
        migrations.CreateModel(
            name='ClubPartnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('club_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnerships_a', to='game.club')),
                ('club_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnerships_b', to='game.club')),
            ],
            options={
                'verbose_name': 'Vereinspartnerschaft',
                'verbose_name_plural': 'Vereinspartnerschaften',
            },
        ),
        migrations.CreateModel(
            name='DealRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('SWAP', 'Tausch'), ('CASH', 'Geld'), ('SWAP_CASH', 'Tausch/Geld'), ('LOAN', 'Leihanfrage')], max_length=10)),
                ('timing', models.CharField(choices=[('SOFORT', 'Sofort'), ('WP', 'Winterpause'), ('SE', 'Saisonende')], default='SOFORT', max_length=6)),
                ('cash_from', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Geld vom Initiator')),
                ('cash_to', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Geld vom Empfänger')),
                ('loan_until', models.CharField(blank=True, choices=[('WP', 'Winterpause'), ('SE', 'Saisonende')], default='', max_length=6)),
                ('loan_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('loan_buy_option', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('message', models.CharField(blank=True, default='', max_length=280)),
                ('status', models.CharField(choices=[('OPEN', 'Offen'), ('ACCEPTED', 'Angenommen'), ('DECLINED', 'Abgelehnt'), ('WITHDRAWN', 'Zurückgezogen'), ('EXPIRED', 'Abgelaufen')], default='OPEN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(verbose_name='Läuft ab am')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('from_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_requests_sent', to='game.club', verbose_name='Initiator')),
                ('to_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_requests_received', to='game.club', verbose_name='Empfänger')),
            ],
            options={
                'verbose_name': 'Deal-Anfrage',
                'verbose_name_plural': 'Deal-Anfragen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DealRequestPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('FROM', 'Initiator'), ('TO', 'Empfänger')], max_length=4)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_request_entries', to='game.player')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game.dealrequest')),
            ],
            options={
                'verbose_name': 'Deal-Spieler',
                'verbose_name_plural': 'Deal-Spieler',
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Leihgebühr (€)')),
                ('until', models.CharField(choices=[('WP', 'Winterpause'), ('SE', 'Saisonende')], max_length=2)),
                ('buy_option', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('started_via', models.CharField(choices=[('LISTING', 'Leihmarkt'), ('DEAL', 'Deal-Anfrage')], default='LISTING', max_length=8)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('recall_requested', models.BooleanField(default=False)),
                ('recall_requested_at', models.DateTimeField(blank=True, null=True)),
                ('loan_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans_in', to='game.club', verbose_name='Leihverein')),
                ('owner_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans_out', to='game.club', verbose_name='Stammverein')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans_v2', to='game.player')),
            ],
            options={
                'verbose_name': 'Leihe',
                'verbose_name_plural': 'Leihen',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_asking', models.DecimalField(decimal_places=2, help_text='≥ 1.000.000 € (0 € nur Partnerverein).', max_digits=15, verbose_name='Leihgebühr (€)')),
                ('until', models.CharField(choices=[('WP', 'Winterpause'), ('SE', 'Saisonende')], max_length=2)),
                ('buy_option_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Aktiv'), ('LOANED', 'Verliehen'), ('WITHDRAWN', 'Zurückgezogen')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_listings', to='game.club', verbose_name='Stammverein')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_listings', to='game.player', verbose_name='Spieler')),
            ],
            options={
                'verbose_name': 'Leih-Listing',
                'verbose_name_plural': 'Leih-Listings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RumorNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('LISTING_CREATED', 'Listing erstellt'), ('BID_PLACED', 'Gebot abgegeben'), ('DEAL_SENT', 'Anfrage gesendet'), ('TRANSFER_DONE', 'Transfer vollzogen'), ('LOAN_DONE', 'Leihe vollzogen')], max_length=16)),
                ('outlet', models.CharField(max_length=80)),
                ('headline', models.CharField(max_length=280)),
                ('sum_mode', models.CharField(choices=[('EXACT', 'Exakt'), ('RANGE', 'Spanne')], default='EXACT', max_length=6)),
                ('reaction', models.CharField(blank=True, choices=[('DENIED', 'Dementiert'), ('NO_COMMENT', 'Kein Kommentar'), ('CONFIRMED', 'Bestätigt')], default='', max_length=10)),
                ('reaction_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('affected_club', models.ForeignKey(blank=True, help_text='Verein, dessen Manager reagieren darf (eigener Verein).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rumor_news', to='game.club')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rumor_news', to='game.player')),
            ],
            options={
                'verbose_name': 'Transfergerücht',
                'verbose_name_plural': 'Transfergerüchte',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='SellOnClause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.PositiveSmallIntegerField(help_text='5–20 %.')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('beneficiary_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_on_clauses', to='game.club')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_on_clauses', to='game.player')),
            ],
            options={
                'verbose_name': 'Weiterverkaufsbeteiligung',
                'verbose_name_plural': 'Weiterverkaufsbeteiligungen',
            },
        ),
        migrations.CreateModel(
            name='SquadOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ALL', 'Alle Angebote'), ('SWAP', 'Tausch'), ('CASH', 'Geld'), ('SWAP_CASH', 'Tausch/Geld'), ('LOAN', 'Leihe'), ('UVK', 'Unverkäuflich')], default='UVK', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='squad_offer', to='game.player', verbose_name='Spieler')),
            ],
            options={
                'verbose_name': 'Kader-Angebot',
                'verbose_name_plural': 'Kader-Angebote',
            },
        ),
        migrations.CreateModel(
            name='TransferListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_bid', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Mindestgebot (€)')),
                ('buy_now', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Sofortkauf (€)')),
                ('timing', models.CharField(choices=[('SOFORT', 'Sofort'), ('WP', 'Winterpause'), ('SE', 'Saisonende')], default='SOFORT', max_length=6, verbose_name='Transferzeitpunkt')),
                ('duration_days', models.PositiveSmallIntegerField(blank=True, help_text='NULL bei Vereinslosen (24 h ab 1. Gebot).', null=True, verbose_name='Laufzeit (Tage)')),
                ('listed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Gelistet am')),
                ('ends_at', models.DateTimeField(blank=True, help_text='NULL bis zum 1. Gebot bei Vereinslosen.', null=True, verbose_name='Endet am')),
                ('extensions', models.PositiveSmallIntegerField(default=0, verbose_name='Anti-Sniping-Verlängerungen')),
                ('status', models.CharField(choices=[('ACTIVE', 'Aktiv'), ('SOLD', 'Verkauft'), ('CANCELLED', 'Storniert'), ('EXPIRED', 'Abgelaufen')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_listings', to='game.player', verbose_name='Spieler')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_listings', to='game.club', verbose_name='Verkäufer (NULL = vereinslos)')),
            ],
            options={
                'verbose_name': 'Transfer-Listing',
                'verbose_name_plural': 'Transfer-Listings',
                'ordering': ['ends_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TransferBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Betrag (€)')),
                ('is_leading', models.BooleanField(default=False, help_text='Genau ein führendes Gebot je aktivem Listing.', verbose_name='Aktuell führend')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_bids_v2', to='game.club', verbose_name='Bietender Verein')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='game.transferlisting', verbose_name='Listing')),
            ],
            options={
                'verbose_name': 'Gebot',
                'verbose_name_plural': 'Gebote',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ListingPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_pins', to='game.club', verbose_name='Verein')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='game.transferlisting', verbose_name='Listing')),
            ],
            options={
                'verbose_name': 'Listing-Pin',
                'verbose_name_plural': 'Listing-Pins',
            },
        ),
        migrations.CreateModel(
            name='TransferRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('kind', models.CharField(choices=[('CASH', 'Kauf'), ('SWAP', 'Tausch'), ('LOAN', 'Leihe'), ('OPTION', 'Kaufoption gezogen'), ('ADMIN', 'Admin-Transfer'), ('FREE', 'Ablösefrei')], max_length=8)),
                ('timing', models.CharField(choices=[('SOFORT', 'Sofort'), ('WP', 'Winterpause'), ('SE', 'Saisonende')], default='SOFORT', max_length=6)),
                ('cash_a', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('cash_b', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('loan_event', models.CharField(blank=True, choices=[('START', 'Leihstart'), ('RETURN', 'Rückkehr')], default='', max_length=6)),
                ('loan_until', models.CharField(blank=True, choices=[('WP', 'Winterpause'), ('SE', 'Saisonende')], default='', max_length=2)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='Admin-storniert')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('club_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_records_a', to='game.club', verbose_name='Verein A (abgebend)')),
                ('club_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_records_b', to='game.club', verbose_name='Verein B (aufnehmend)')),
            ],
            options={
                'verbose_name': 'Transfer-Historieneintrag',
                'verbose_name_plural': 'Transfer-Historie',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TransferLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locked_until', models.DateField(verbose_name='Gesperrt bis')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_locks', to='game.player')),
                ('source_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_locks', to='game.transferrecord')),
            ],
            options={
                'verbose_name': 'Wechselsperre',
                'verbose_name_plural': 'Wechselsperren',
                'ordering': ['-locked_until'],
            },
        ),
        migrations.CreateModel(
            name='PendingTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execute_at', models.DateField(verbose_name='Vollzug am (WP/SE-Datum)')),
                ('source', models.CharField(choices=[('LISTING', 'Listing'), ('DEAL', 'Deal'), ('OPTION', 'Kaufoption')], max_length=8)),
                ('status', models.CharField(choices=[('PENDING', 'Ausstehend'), ('EXECUTED', 'Vollzogen'), ('CANCELLED_ADMIN', 'Admin-storniert')], default='PENDING', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('from_club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_transfers_out', to='game.club')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_transfers', to='game.player')),
                ('to_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_transfers_in', to='game.club')),
                ('record', models.ForeignKey(blank=True, help_text='Historieneintrag, der bereits beim Zuschlag entstand.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_transfers', to='game.transferrecord')),
            ],
            options={
                'verbose_name': 'Ausstehender Transfer',
                'verbose_name_plural': 'Ausstehende Transfers',
                'ordering': ['execute_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TransferRecordPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('A', 'Von A'), ('B', 'Von B')], max_length=1)),
                ('market_value_at_transfer', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_record_entries', to='game.player')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game.transferrecord')),
            ],
            options={
                'verbose_name': 'Historie-Spieler',
                'verbose_name_plural': 'Historie-Spieler',
            },
        ),
        migrations.CreateModel(
            name='TransferReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=500, verbose_name='Begründung (Pflicht)')),
                ('status', models.CharField(choices=[('OPEN', 'Offen'), ('DISMISSED', 'Abgewiesen'), ('UNDER_REVIEW', 'In Überprüfung (Sportgericht)')], default='OPEN', max_length=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='game.transferrecord')),
                ('reporter_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_reports', to='game.club')),
            ],
            options={
                'verbose_name': 'Transfer-Meldung',
                'verbose_name_plural': 'Transfer-Meldungen',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='YouthLevyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.DecimalField(decimal_places=3, max_digits=6)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payer_club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='youth_levies_paid', to='game.club')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='youth_levy_payments', to='game.player')),
                ('receiver_club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='youth_levies_received', to='game.club')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='youth_levies', to='game.transferrecord')),
            ],
            options={
                'verbose_name': 'Jugendabgabe-Buchung',
                'verbose_name_plural': 'Jugendabgabe-Buchungen',
            },
        ),
        migrations.AddIndex(
            model_name='dealrequest',
            index=models.Index(fields=['status', 'expires_at'], name='game_dealre_status_74d624_idx'),
        ),
        migrations.AddIndex(
            model_name='dealrequest',
            index=models.Index(fields=['to_club', 'status'], name='game_dealre_to_club_1ba426_idx'),
        ),
        migrations.AddIndex(
            model_name='dealrequest',
            index=models.Index(fields=['from_club', 'status'], name='game_dealre_from_cl_905e72_idx'),
        ),
        migrations.AddConstraint(
            model_name='dealrequestplayer',
            constraint=models.UniqueConstraint(fields=('request', 'player'), name='unique_deal_request_player'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['owner_club', 'ended_at'], name='game_loan_owner_c_625860_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['loan_club', 'ended_at'], name='game_loan_loan_cl_732f47_idx'),
        ),
        migrations.AddIndex(
            model_name='loanlisting',
            index=models.Index(fields=['status'], name='game_loanli_status_25a068_idx'),
        ),
        migrations.AddIndex(
            model_name='rumornews',
            index=models.Index(fields=['-published_at'], name='game_rumorn_publish_bce338_idx'),
        ),
        migrations.AddIndex(
            model_name='transferlisting',
            index=models.Index(fields=['status', 'ends_at'], name='game_transf_status_e3a51d_idx'),
        ),
        migrations.AddIndex(
            model_name='transferlisting',
            index=models.Index(fields=['seller', 'status'], name='game_transf_seller__518ae8_idx'),
        ),
        migrations.AddIndex(
            model_name='transferbid',
            index=models.Index(fields=['listing', '-created_at'], name='game_transf_listing_70afaf_idx'),
        ),
        migrations.AddIndex(
            model_name='transferbid',
            index=models.Index(fields=['club', 'is_leading'], name='game_transf_club_id_d44d27_idx'),
        ),
        migrations.AddConstraint(
            model_name='listingpin',
            constraint=models.UniqueConstraint(fields=('listing', 'club'), name='unique_listing_pin'),
        ),
        migrations.AddIndex(
            model_name='transferrecord',
            index=models.Index(fields=['kind', '-date'], name='game_transf_kind_aef018_idx'),
        ),
        migrations.AddIndex(
            model_name='transferrecord',
            index=models.Index(fields=['-date'], name='game_transf_date_68f3c1_idx'),
        ),
        migrations.AddIndex(
            model_name='transferlock',
            index=models.Index(fields=['player', 'locked_until'], name='game_transf_player__327421_idx'),
        ),
        migrations.AddIndex(
            model_name='pendingtransfer',
            index=models.Index(fields=['status', 'execute_at'], name='game_pendin_status_7562b0_idx'),
        ),
    ]
