# Generated by Django 6.0.7 on 2026-08-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0155_seed_transfer_v2_params'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingtransfer',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Ausstehend'), ('EXECUTED', 'Vollzogen'), ('CANCELLED_ADMIN', 'Admin-storniert'), ('CANCELLED_LIMIT', 'Kadergrenzen-Storno')], default='PENDING', max_length=16),
        ),
    ]
