# Generated by Django 6.0.7 on 2026-08-12 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0156_pendingtransfer_status_cancelled_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='rumornews',
            name='published_day',
            field=models.DateField(blank=True, help_text='Dedup-Tag: max. 1 Gerücht je Spieler+Event-Typ+Tag (DB-erzwungen; NULL bei Gerüchten ohne Spieler).', null=True),
        ),
        migrations.AddConstraint(
            model_name='rumornews',
            constraint=models.UniqueConstraint(condition=models.Q(('player__isnull', False), ('published_day__isnull', False)), fields=('player', 'event_type', 'published_day'), name='uniq_rumor_player_event_day'),
        ),
    ]
