# Generated by Django 6.0.7 on 2026-08-12 22:16

from django.db import migrations, models
from django.utils import timezone


def backfill_published_day(apps, schema_editor):
    """Bestandsdaten: Spieler-Gerüchte bekommen ihren Dedup-Tag.

    Kollidieren dadurch mehrere Alt-Gerüchte desselben Spielers/Event-Typs
    am selben Tag mit dem UniqueConstraint aus 0157, bleibt das ÄLTESTE
    bestehen; jüngere Duplikate verletzen die 1-pro-Tag-Regel per Design
    und werden entfernt.
    """
    RumorNews = apps.get_model('game', 'RumorNews')
    seen = set()
    for r in (RumorNews.objects.filter(
                player__isnull=False, published_day__isnull=True)
              .order_by('published_at', 'pk')):
        day = timezone.localtime(r.published_at).date() \
            if r.published_at else timezone.localdate()
        key = (r.player_id, r.event_type, day)
        exists = RumorNews.objects.filter(
            player_id=r.player_id, event_type=r.event_type,
            published_day=day).exists()
        if key in seen or exists:
            r.delete()
            continue
        seen.add(key)
        r.published_day = day
        r.save(update_fields=['published_day'])


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0157_rumor_news_daily_dedup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rumornews',
            name='published_day',
            field=models.DateField(blank=True, help_text='Dedup-Tag: max. 1 Gerücht je Spieler+Event-Typ+Tag. Bei Spieler-Gerüchten PFLICHT (CheckConstraint + save()-Autofill); NULL nur ohne Spieler.', null=True),
        ),
        migrations.RunPython(backfill_published_day,
                             migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='rumornews',
            constraint=models.CheckConstraint(condition=models.Q(('player__isnull', True), ('published_day__isnull', False), _connector='OR'), name='rumor_player_requires_day'),
        ),
    ]
