# Generated by Django 6.0.7 on 2026-08-13 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0158_rumor_player_requires_day'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=40, verbose_name='Aktion')),
                ('target', models.CharField(max_length=200, verbose_name='Ziel')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Details')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_action_logs', to=settings.AUTH_USER_MODEL, verbose_name='Akteur')),
            ],
            options={
                'verbose_name': 'Creator-Aktionsprotokoll',
                'verbose_name_plural': 'Creator-Aktionsprotokolle',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SquadLimitNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Text')),
                ('status', models.CharField(choices=[('OPEN', 'Offen'), ('SPORTGERICHT', 'Im Sportgericht')], default='OPEN', max_length=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squad_limit_notes', to='game.club', verbose_name='Verein')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='squad_limit_notes', to='game.player', verbose_name='Spieler')),
            ],
            options={
                'verbose_name': 'Kadergrenzen-Vermerk',
                'verbose_name_plural': 'Kadergrenzen-Vermerke',
                'ordering': ['-created_at'],
            },
        ),
    ]
