# Generated by Django 6.0.7 on 2026-08-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0159_creator_transferaufsicht_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferreport',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Offen'), ('DISMISSED', 'Abgewiesen'), ('UNDER_REVIEW', 'In Überprüfung (Sportgericht)'), ('CONFIRMED', 'Bestätigt (Sportgericht)')], default='OPEN', max_length=14),
        ),
    ]
