# Generated by Django 6.0.7 on 2026-08-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0160_alter_transferreport_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealrequest',
            name='counter_offer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Gegenforderung (€)'),
        ),
        migrations.AlterField(
            model_name='dealrequest',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Offen'), ('COUNTER', 'Gegenforderung'), ('ACCEPTED', 'Angenommen'), ('DECLINED', 'Abgelehnt'), ('WITHDRAWN', 'Zurückgezogen'), ('EXPIRED', 'Abgelaufen')], default='OPEN', max_length=10),
        ),
    ]
