# Generated by Django 6.0.7 on 2026-08-25 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0161_dealrequest_counter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricCoach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fm_inside_id', models.CharField(max_length=80, unique=True, verbose_name='FM-Inside-ID')),
                ('name', models.CharField(max_length=160, verbose_name='Name')),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Historischer Trainer',
                'verbose_name_plural': 'Historische Trainer',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClubRecordCorrectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_key', models.CharField(max_length=60)),
                ('old_value', models.CharField(blank=True, max_length=160)),
                ('new_value', models.CharField(max_length=160)),
                ('new_holder', models.CharField(blank=True, max_length=160)),
                ('new_date', models.CharField(blank=True, max_length=40)),
                ('source_reference', models.TextField()),
                ('requester_note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Offen'), ('accepted', 'Angenommen'), ('rejected', 'Abgelehnt')], default='open', max_length=20)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hall_of_fame_correction_requests', to='game.club')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_hall_of_fame_correction_requests', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hall_of_fame_correction_requests', to='game.managerprofile')),
            ],
            options={
                'verbose_name': 'Rekordkorrekturantrag',
                'verbose_name_plural': 'Rekordkorrekturanträge',
                'ordering': ['status', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClubRecordBreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_key', models.CharField(max_length=60)),
                ('old_value_numeric', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('old_value_display', models.CharField(blank=True, max_length=160)),
                ('old_holder_name', models.CharField(blank=True, max_length=160)),
                ('new_value_numeric', models.DecimalField(decimal_places=2, max_digits=15)),
                ('new_value_display', models.CharField(max_length=160)),
                ('new_holder_name', models.CharField(max_length=160)),
                ('broke_seed', models.BooleanField(default=False)),
                ('season', models.CharField(blank=True, max_length=20)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hall_of_fame_record_breaks', to='game.club')),
            ],
            options={
                'verbose_name': 'Rekordwechsel',
                'verbose_name_plural': 'Rekordwechsel',
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['club', 'record_key', '-occurred_at'], name='game_clubre_club_id_c4117f_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClubRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_key', models.CharField(max_length=60)),
                ('source', models.CharField(choices=[('SEED', 'Echte Geschichte'), ('SIM', 'Neue Geschichte')], max_length=4)),
                ('value_numeric', models.DecimalField(decimal_places=2, max_digits=15)),
                ('value_display', models.CharField(max_length=160)),
                ('holder_name', models.CharField(max_length=160)),
                ('opponent_name', models.CharField(blank=True, max_length=160)),
                ('context_line', models.CharField(blank=True, max_length=200)),
                ('record_date', models.DateField(blank=True, null=True)),
                ('period_from', models.DateField(blank=True, null=True)),
                ('period_to', models.DateField(blank=True, null=True)),
                ('season', models.CharField(blank=True, max_length=20)),
                ('competition', models.CharField(blank=True, max_length=120)),
                ('source_note', models.TextField(blank=True)),
                ('is_anonymized', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hall_of_fame_records', to='game.club')),
                ('holder_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='game.managerprofile')),
                ('holder_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='game.player')),
                ('linked_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hall_of_fame_records', to='game.simulatedmatch')),
                ('opponent_club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='game.club')),
                ('holder_coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='game.historiccoach')),
            ],
            options={
                'verbose_name': 'Vereinsrekord',
                'verbose_name_plural': 'Vereinsrekorde',
                'indexes': [
                    models.Index(fields=['club', 'source'], name='game_clubre_club_id_3d22da_idx'),
                    models.Index(fields=['record_key', 'source'], name='game_clubre_record__712291_idx'),
                ],
                'constraints': [models.UniqueConstraint(fields=('club', 'record_key', 'source'), name='unique_club_record_source')],
            },
        ),
    ]