# Generated by Django 6.0.7 on 2026-08-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0162_historiccoach_clubrecordcorrectionrequest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubrecordbreak',
            name='new_holder_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='clubrecordbreak',
            name='new_value_display',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='clubrecordbreak',
            name='new_value_numeric',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]