# Generated by Django 6.0.7 on 2026-08-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0163_alter_clubrecordbreak_new_value_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulatedmatch',
            name='match_type',
            field=models.CharField(
                choices=[
                    ('liga', 'Ligaspiel'),
                    ('freundschaft', 'Freundschaftsspiel'),
                    ('pokal', 'Pokal'),
                ],
                default='freundschaft',
                max_length=20,
                verbose_name='Spieltyp',
            ),
        ),
    ]