# Generated by Django 6.0.7 on 2026-08-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0164_alter_simulatedmatch_match_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubrecord',
            name='custom_label',
            field=models.CharField(
                blank=True,
                help_text='Freie Bezeichnung für die zwei offenen Vereinsrekordplätze.',
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name='clubrecordcorrectionrequest',
            name='custom_label',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='clubrecordcorrectionrequest',
            name='new_competition',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='clubrecordcorrectionrequest',
            name='new_context',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='clubrecordcorrectionrequest',
            name='new_numeric_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='clubrecordcorrectionrequest',
            name='new_season',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]