# Generated by Django 6.0.7 on 2026-08-04 18:13

import django.db.models.deletion
import showauction.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0153_financereservation_notification_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowAuctionPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Name')),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('color_hex', models.CharField(default='#ffd400', help_text='Hex-Farbe des Typs (nie Cyan — Cyan ist Funktionsfarbe).', max_length=7, verbose_name='Typfarbe')),
                ('icon', models.CharField(blank=True, default='', max_length=40)),
                ('rules_text', models.TextField(blank=True, default='', help_text='Menschlich lesbare Regeln fürs Regelpanel der Detailseite.', verbose_name='Regeltext')),
                ('config', models.JSONField(default=dict, help_text='Belegung der 16 Regel-Achsen (validator.validate_config).')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Auktions-Preset',
                'verbose_name_plural': 'Auktions-Presets',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ShowAuction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_snapshot', models.JSONField(default=dict)),
                ('type_name', models.CharField(blank=True, default='', max_length=80)),
                ('color_hex', models.CharField(default='#ffd400', max_length=7)),
                ('rules_text', models.TextField(blank=True, default='')),
                ('player_prev_pool_status', models.CharField(default='none', help_text='Pool-Status vor Raum-Eintritt — Rückweg bei failed/cancelled.', max_length=20)),
                ('hero_image', models.ImageField(blank=True, help_text='Freigestelltes Hero-Bild (serverseitig via rembg).', null=True, upload_to=showauction.models.hero_upload_path)),
                ('media_logo', models.ImageField(blank=True, help_text='Medienlogo — wird NIE freigestellt, liegt auf dunkler Trägerfläche.', null=True, upload_to=showauction.models.logo_upload_path)),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('scheduled', 'Geplant'), ('running', 'Läuft'), ('settled', 'Zugeschlagen'), ('failed', 'Geplatzt'), ('cancelled', 'Abgebrochen')], default='draft', max_length=12)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('start_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('market_value_snapshot', models.DecimalField(blank=True, decimal_places=2, help_text='MW des Spielers bei Anlage — Basis aller Prozent-Formeln.', max_digits=14, null=True)),
                ('hidden_target', models.DecimalField(blank=True, decimal_places=2, help_text='Bereichsauktion: verborgene Korridor-Mitte (nie offenlegen).', max_digits=14, null=True)),
                ('hidden_width', models.DecimalField(blank=True, decimal_places=2, help_text='Bereichsauktion: Korridor-Gesamtbreite in Euro.', max_digits=14, null=True)),
                ('hold_step_index', models.PositiveSmallIntegerField(default=0)),
                ('extension_count', models.PositiveIntegerField(default=0)),
                ('endspurt_notified', models.BooleanField(default=False)),
                ('conditions', models.JSONField(blank=True, default=list, help_text='Teilnahmebedingungen (Achse 12) — Liste von {art, …}.')),
                ('winning_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('fail_reason', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='show_auctions', to='game.player')),
                ('winner_club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='show_auction_wins', to='game.club')),
                ('preset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auctions', to='showauction.showauctionpreset')),
            ],
            options={
                'verbose_name': 'Show-Auktion',
                'verbose_name_plural': 'Show-Auktionen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShowAuctionWatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('bid', 'Gebot'), ('manual', 'Manuell')], default='manual', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watches', to='showauction.showauction')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='show_auction_watches', to='game.club')),
            ],
            options={
                'verbose_name': 'Auktions-Beobachtung',
                'verbose_name_plural': 'Auktions-Beobachtungen',
            },
        ),
        migrations.CreateModel(
            name='ShowAuctionBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('is_leading', models.BooleanField(default=False)),
                ('coin_charged', models.BooleanField(default=False, help_text='Eintrittsticket (Hoeneß-Coin) wurde mit diesem Gebot bezahlt.')),
                ('reservation_ref', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='showauction.showauction')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='show_auction_bids', to='game.club')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='show_auction_bids', to='game.managerprofile')),
            ],
            options={
                'verbose_name': 'Auktionsgebot',
                'verbose_name_plural': 'Auktionsgebote',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['auction', 'is_active'], name='showauction_auction_f35f6c_idx'), models.Index(fields=['club', 'is_active'], name='showauction_club_id_0c0812_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='showauction',
            index=models.Index(fields=['status', 'ends_at'], name='showauction_status_a0ac32_idx'),
        ),
        migrations.AddIndex(
            model_name='showauction',
            index=models.Index(fields=['status', 'starts_at'], name='showauction_status_c6b408_idx'),
        ),
        migrations.AddConstraint(
            model_name='showauctionwatch',
            constraint=models.UniqueConstraint(fields=('auction', 'club'), name='unique_show_auction_watch'),
        ),
    ]
